### ISSUE TITLE
Wrap Darknet yolov4 in Sahi's slicing

### ISSUE THREAD

**Issue by wjassim** [obss/sahi#101]
Hi. Thank you for the great tool.

I am wondering if it is possible to wrap darknet-based yolov4 (https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py) in Sahi's slicing detection. The darknet-based yolov4 (darknet_video.py) provides detections in the following format:

class (str),
confidence (one value in str), and
bbox (a tuple with 4 values).

This is shown in the following image:

![image](https://user-images.githubusercontent.com/67051480/119113728-4e92e600-ba1d-11eb-883a-f6b677cceea2.png)

Thanks a million.

**Comment by fcakyon** [comment]
@wjassim thanks for your interest, we are currently working on [ultralytics/yolov5](https://github.com/ultralytics/yolov5) integration. It is faster and have greater accuracy than darknet/yolov4. I belive it will satisfy your needs. 

Moreover, it is not that hard to add custom model support for sahi tool. You can follow these steps to add custom model support and we will accept your PR: https://github.com/obss/sahi#adding-new-detection-framework-support

**Comment by wjassim** [comment]
Thank you @fcakyon. Looking forward to trying the new integration.

**Comment by fcakyon** [comment]
@wjassim will keep you updated.

In the meantime you can take a look at [yolov5 pacakge](https://github.com/fcakyon/yolov5-pip). Training is easy as:

```bash
$ yolo_train --data coco.yaml --cfg yolov5s.yaml --weights '' --batch-size 64
                                    yolov5m                                40
                                    yolov5l                                24
                                    yolov5x                                16
```

Inference is easy as:

```bash
$ yolo_detect --source 0  # webcam
                       file.jpg  # image
                       file.mp4  # video
                       path/  # directory
                       path/*.jpg  # glob
                       rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa  # rtsp stream
                       rtmp://192.168.1.105/live/test  # rtmp stream
                       http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8  # http stream
```

No need for manual compile or git clone, `pip install yolov5` is enough and you can start training from CLI.

**Comment by wjassim** [comment]
Thank you very much @fcakyon. I will try yolov5 now. Will pip install yolov5 install the yolov5 with the gpu support?

**Comment by fcakyon** [comment]
@wjassim yes, as default it uses gpu.

**Comment by fcakyon** [comment]
@wjassim yolov5 support has been added with `v0.4.0` release.

Please update sahi with `pip install -U sahi` and install yolov5 with `pip install yolov5`. 

Check [yolov5 demo notebook](https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb) for detailed usage.

**Comment by wjassim** [comment]
@fcakyon thank you for the update. Can't wait to try it out. Best regards
