### ISSUE TITLE
coco2yolov5 script error

### ISSUE THREAD

**Issue by ed-muthiah** [obss/sahi#114]
Hello I'm getting a strange error when trying to use the coco to yolov5 script.

```
(coco2yolo) C:\Users\Annamalai\Documents\sahi>python scripts/coco2yolov5.py 
--coco_file "C:\Users\Annamalai\Documents\data\my_dataset.json" 
--source "C:\Users\Annamalai\Documents\data\my_dataset\images" --train_split 0.8                  
indexing coco dataset annotations...                                                                                                                                         100%|
████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11777/11777 [00:00<00:00, 1169586.55it/s]
generating image symlinks and annotation files for yolov5...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1600/1600 [00:16<00:00, 97.64it/s]
generating image symlinks and annotation files for yolov5...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 401/401 [00:08<00:00, 45.32it/s]
multiprocessing.pool.RemoteTraceback:                                                                                                                                        
"""                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                             
File "C:\Users\Annamalai\anaconda3\envs\coco2yolo\lib\multiprocessing\pool.py", line 119, in worker
   result = (True, func(*args, **kwds))
File "C:\Users\Annamalai\anaconda3\envs\coco2yolo\lib\multiprocessing\pool.py", line 47, in starmapstar
   return list(itertools.starmap(args[0], args[1]))
File "C:\Users\Annamalai\anaconda3\envs\coco2yolo\lib\site-packages\sahi\utils\coco.py", line 1389, in export_single_yolov5_image_and_corresponding_txt
   with open(yolo_annotation_path, "w") as outfile:                                                                                                                         
FileNotFoundError: [Errno 2] No such file or directory:
'.txtC.txt:.txt\\.txtU.txts.txte.txtr.txts.txt\\.txtA.txtn.txtn.txta.txtm.txta.txtl.txta.txti.txt\\.txtD.txto.txtc.txtu.txtm.txte.txtn.txtt.txts.txt\\.tx
ts.txti.txtg.txth.txtt.txtd.txta.txtt.txta.txt\\.txtd.txta.txtt.txta.txt\\.txts.txta.txth.txti.txt\\.txtr.txtu.txtn.txts.txt\\.txtc.txto.txtc.txto.txt2.txt
y.txto.txtl.txto.txtv.txt5.txt\\.txte.txtx.txtp.txt\\.txtv.txta.txtl.txt\\.txts.txtt.txto.txtc.txtk.txt-.txtp.txth.txto.txtt.txto.txt-.txts.txtt.txto.txtp
.txt-.txts.txti.txtg.txtn.txt-.txta.txtn.txtd.txt-.txtt.txtr.txta.txtf.txtf.txti.txtc.txt-.txtl.txti.txtg.txth.txtt.txts.txt-.txta.txtt.txt-.txtt.txth.txte.txt
-.txtb.txte.txtg.txti.txtn.txtn.txti.txtn.txtg.txt-.txto.txtf.txt-.txta.txt-.txtc.txto.txtn.txts.txtt.txtr.txtu.txtc.txtt.txti.txto.txtn.txt-.txts.txti.txtt
.txte.txt-.txta.txtl.txto.txtn.txtg.txt-.txta.txt-.txtm.txto.txtu.txtn.txtt.txta.txti.txtn.txt-.txtr.txto.txta.txtd.txt-.txtt.txtr.txta.txtf.txtf.txti.txtc.
txt-.txt4.txt5.txt0.txtw.txt-.txt1.txt4.txt8.txt5.txt' 
```

**Comment by fcakyon** [comment]
@ed-muthiah thanks a lot for describing this issue.

This error should be fixed with https://github.com/obss/sahi/pull/115.

Can you try with updated [coco2yolo.py](https://github.com/obss/sahi/blob/main/scripts/coco2yolov5.py) file and report back?

**Comment by ed-muthiah** [comment]
Thanks for the help fcakyon. Do you need to update the pip wheel before I reinstall it? I can't seem to run the script from just the cloned repo. Or can I reinstall it locally?

python -m pip install -e C:\Users\Annamalai\Documents\sahi

**Comment by ed-muthiah** [comment]
There's a chance it's a file name issue with the code
![image](https://user-images.githubusercontent.com/59877549/120910886-f539e080-c6c5-11eb-8f6e-4538f7c82b2f.png)

**Comment by ed-muthiah** [comment]
Hey @fcakyon I found the error. It seems that one of my images for some odd reason had no file type such as `image20**.png**` or `image20**.jpg**` it was just `image20`. I found this by putting `print("Current file name", coco_image.file_name)` in line 1362 of `coco.py`. It might be good to put a try/catch if an incorrect image format or name is provided. Thanks for your help with this. 

P.S. Outside of sahi I think this coco2yolov5 script is something that a fair few people would be interested in so it might be worth breaking it out into a new repo?

**Comment by fcakyon** [comment]
@ed-muthiah you mean the `No such file or directory: '.txtC.txt:.txt\\.` error is caused by missing file type? After fixing it all errors are gone? If that is the case, I can add a type check in the code as you mentioned 👍

**Comment by fcakyon** [comment]
@ed-muthiah you are right on your second point. coco2yolov5 script can be published as a separate repo. We are thinking of publishing it on a new repo once everything is more stable 👍

**Comment by ed-muthiah** [comment]
@fcakyon Yeah that's right, after adding a proper file extension, the problem is fixed and I now get the correct conversion.

**Comment by fcakyon** [comment]
@ed-muthiah thanks a lot for the feedbacks!

Added warning for opening the cmd prompt as admin with https://github.com/obss/sahi/pull/120, and added pyyaml into requirements with https://github.com/obss/sahi/pull/119, now working on file type check.

All updates will be live with v0.4.4 release :)

**Comment by ed-muthiah** [comment]
Thanks for the quick responses I'll close this now. Happy to contribute to the new repo when you get it going :)
