### ISSUE TITLE
Sahi with multi-gpu

### ISSUE THREAD

**Issue by wjassim** [obss/sahi#121]
Hi @fcakyon, 

Thank you for providing this tool. I was wondering if sahi supports detections with multi-gpu. I mean is it possible for sahi to detect objects from the obtained tiles using more than one gpu in parallel to speed up the process?

**Comment by fcakyon** [comment]
@wjassim thanks a lot for your interest in this repo!

It is in our to-do list but there is no ETA. We accept any related PR :)

**Comment by fcakyon** [comment]
closing since it is not in our priority. we are open to any pr!
