### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by fcakyon** [obss/sahi#124]

**Comment by weiji14** [comment]
Hi there, thanks for this great library! I was wondering if the conda package could be updated to include Python 3.9 too. At the moment, https://anaconda.org/obss/sahi/files?version=0.8.0 is only showing support up to Python 3.8. Thanks :grin:

**Comment by fcakyon** [comment]
@weiji14 thanks for your interest!

We are about to drop conda support. Currently sahi pypi package supports Python 3.9. You can install sahi for Python 3.9 using `pip install -U sahi`.

**Comment by weiji14** [comment]
Ah I see, is there a reason for dropping conda support? If it's to do with maintenance overhead, I can help start a community maintained conda-forge package for sahi.

**Comment by fcakyon** [comment]
@weiji14 yes the reason was maintenance overhead. Would be awesome if you could help starting conda-forge package!
