### ISSUE TITLE
tensorflow object detection api support

### ISSUE THREAD

**Issue by javierIA** [obss/sahi#155]
Do you plan to add more frameworks e.g. one object detection tensorflow api

**Comment by fcakyon** [comment]
@javierIA it can be easily extended to other frameworks. See contributing section: https://github.com/obss/sahi#contributing

If you provide sample code for getting bounding boxes/scores etc via tensorflow api I can add the support for it.

**Comment by fcakyon** [comment]
closing this since no priority, feel free to open a pr
