### ISSUE TITLE
Slicing huge tiff file with coco formatted labels 

### ISSUE THREAD

**Issue by abfleishman** [obss/sahi#173]
[[Huge Apologies for this poorly framed issue/question without any reproducibility etc!!]]

I have a set of large tiff files >10,000x10,000 px with masks in COCO JSON format.  I am attempting to use `sahi` to slice the dataset to create training data.  It has taken some modification to read files with `skimage` instead of `PIL` but it seems like my copy of `sahi` is now able to read the images and create the sliced tiff files as outputs. 

The issue I am having is in the annotations.  The bounding boxes are being sliced but the segmentation field is empty in the output json.  I am using `sahi.slice_coco` to read the coco dataset and slice it.  

Digging into the code a little to attempt to troubleshoot, it looks like the segmentations are not being sliced?!  https://github.com/obss/sahi/blob/03e5191dff1f96e268ca523d0a2da6c70a5b88a9/sahi/utils/coco.py#L200

Is this intentional?  Am I missing something?  This package is exactly what I am looking for so I hope you can help me out!

**Comment by fcakyon** [comment]
@abfleishman thanks a lot for using this library! SAHI supports segmentation slicing.

Your provided `get_sliced_coco_annotation` functions takes both box and segmentation slice using the `slice_bbox`. 

If the segmentation output is empty in the final json, there is an unintended bug. I will try my best to find it.

**Comment by fcakyon** [comment]
@abfleishman i think i found the bug. this function is wrong: https://github.com/obss/sahi/blob/03e5191dff1f96e268ca523d0a2da6c70a5b88a9/sahi/utils/coco.py#L134

before this line: https://github.com/obss/sahi/blob/03e5191dff1f96e268ca523d0a2da6c70a5b88a9/sahi/utils/coco.py#L156

this line should be added:
```python
coco_annotation._segmentation = shapely_annotation.to_coco_segmentation()
```

**Comment by fcakyon** [comment]
@abfleishman can you please try this update and report back?

**Comment by abfleishman** [comment]
@fcakyon That fixed it!  Thank you so much!  (I thought I was making a mistake! I am happy I am not crazy and that it was a real bug!  Thank you so much for your swift reply!

**Comment by fcakyon** [comment]
@abfleishman thank you so much for your valuable contribution!

Would you mind showing your image reading modifications for large images? I would gladly add tiff image support to SAHI :)

**Comment by abfleishman** [comment]
I have pushed my changes to a fork [here](https://github.com/ConservationMetrics/sahi).  There are 3 commits.   I have not finished checking that I am reading the images correctly (they display reasonably well, but I want to make sure that the channels are read in the same order.  I also worked around a error in the intersection step on a few of my annotations.

**Comment by abfleishman** [comment]
@fcakyon FYI I am not sure the method I am using for reading in images (`skimage.io.imread` -> `Image.fromarray`) is producing the `PIL` object correctly.  I am working with 4 band images (RGB + Thermal) and they come out looking strange (mostly black).  I am testing with a `normal` 3-band image and the results look good, so I am thinking the 4th band is getting switched with one of the color channels.  I will let you know if I figure it out.

**Comment by fcakyon** [comment]
please let me know if you find a stable way of reading large multi channel tiff files.

would be also great if you could provide me a sample image file that is not confidential.

**Comment by abfleishman** [comment]
Yeah it is not that the images are confidential it is that they are huge!  I will see what I can do to shrink one...

**Comment by fcakyon** [comment]
@abfleishman you can upload the image to google drive and share the url here if you want :)

**Comment by abfleishman** [comment]
https://drive.google.com/file/d/167NDnohZM8Lk5VuKE0XWtkEMM9X63eOF/view?usp=sharing

**Comment by fcakyon** [comment]
@abfleishman you have to open sharing options for the url, i have sent you access request :)

**Comment by abfleishman** [comment]
@fcakyon Done!

**Comment by abfleishman** [comment]
@fcakyon using `skimage.io.imread` worked correctly for the 3 channel images (I am saving to png for now) and that is what let me train a model.

**Comment by fcakyon** [comment]
so skimage.io.imread is enough for reading tiff images right? thats good to know 👍

**Comment by abfleishman** [comment]
Yes I think so.  I had to pip install `imagecodecs` also

**Comment by fcakyon** [comment]
@abfleishman I have added tiff image reading in 0.7.2: https://github.com/obss/sahi/releases/tag/0.7.2

Could you try with the latest version? `pip install -U sahi`

**Comment by abfleishman** [comment]
If appears to have worked flawlessly for `slice_image`, though see #187 and #186
