### ISSUE TITLE
Idea: Parallel Processing for slicing images?  

### ISSUE THREAD

**Issue by abfleishman** [obss/sahi#175]
I was just thinking about if we could slice/write images in parallel and thought I would leave a note here.  It is taking me ~10 minutes to slice 4 large tif files.  and the slow part seems to be saving all the new images but it only uses 1 core.

**Comment by fcakyon** [comment]
@abfleishman good point, its in our high priority todo list now 👍

**Comment by fcakyon** [comment]
@abfleishman I have added concurrent slice export in 0.7.2: https://github.com/obss/sahi/releases/tag/0.7.2

Coud you try with the latest version? `pip install -U sahi`

**Comment by abfleishman** [comment]
I just ran slice_image and it was so fast I thought that it failed silently!!!!  Nice work and thank you!
