### ISSUE TITLE
get_sliced_predictions fails with slices with no predicitons?

### ISSUE THREAD

**Issue by abfleishman** [obss/sahi#186]
I think the `get_sliced_predictions` fails when it files slices with no predictions?  the other possibility is that with these tiff files there are slices that have little or no information (blank parts of the image where no data was collected by the drone).

This is with an image already loaded.  The models Ihave trained only expect 3-channels so I am loading the image and removing the 4th channel to get this to run.

```

# import required functions, classes
from sahi.model import MmdetDetectionModel
from sahi.predict import get_prediction, get_sliced_prediction, predict
from skimage.io import imread
import numpy as np

# #cascade
# model_path="/home/cmi/work_dirs/cascade_mask_rcnn_r50_fpn_1x_eseal_v2/epoch_100.pth"
# config_path="/home/cmi/work_dirs/cascade_mask_rcnn_r50_fpn_1x_eseal_v2/cascade_mask_rcnn_r50_fpn_1x_eseal_v2.py"

#mask
model_path="/home/cmi/work_dirs/mask_rcnn_r50_fpn_1x_coco_eseal_v1/epoch_200.pth"
config_path="/home/cmi/work_dirs/mask_rcnn_r50_fpn_1x_coco_eseal_v1/mask_rcnn_r50_fpn_1x_coco_eseal_v1.py"


# im_path="/home/cmi/eSeals/data_tiled_2048_png_rgb_nooverlap/20200224 FINAL_transparent_reflectance_grayscale_warped_4096_6144_6144_8192.png"
# im_path="/home/cmi/eSeals/data_tiled_1024_png_rgb_20overlap/20200224 FINAL_transparent_reflectance_grayscale_warped_2048_7168_3072_8192.png"
# im_path="/home/cmi/eSeals/data_tiled_1024_png_rgb_20overlap/20200403 Thermal FINAL_transparent_reflectance_grayscale_warped_5120_7168_6144_8192.png"
im_path="/home/cmi/eSeals/data/20200224 FINAL_transparent_reflectance_grayscale_warped.tif"
detection_model = MmdetDetectionModel(
    model_path=model_path,
    config_path=config_path,
    confidence_threshold=0.,
    device="cuda", # or 'cuda'
)

im=imread(im_path)[:,:,0:3].astype(np.uint8)

result = get_sliced_prediction(
    im,
    detection_model,
    slice_height = 1024,
    slice_width = 1024,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)
```

> Number of slices: 240
> Traceback (most recent call last):
> 
>   File "/tmp/ipykernel_6561/4252192217.py", line 7, in <module>
>     overlap_width_ratio = 0.2
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/predict.py", line 221, in get_sliced_prediction
>     slice_image_result.original_image_width,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/predict.py", line 72, in get_prediction
>     full_shape=full_shape,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/model.py", line 139, in convert_original_predictions
>     full_shape=full_shape,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/model.py", line 304, in _create_object_prediction_list_from_original_predictions
>     full_shape=full_shape,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/prediction.py", line 81, in __init__
>     full_shape=full_shape,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/annotation.py", line 536, in __init__
>     self.bbox = BoundingBox(bbox, shift_amount)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/annotation.py", line 32, in __init__
>     if box[0] < 0 or box[1] < 0 or box[2] < 0 or box[3] < 0:
> 
> IndexError: list index out of range

**Comment by fcakyon** [comment]
@abfleishman empty predictions doesnt result in error, sahi can handle it properly. 

It works perfectly on my end with the following code block:

```python
from sahi.utils.mmdet import MmdetTestConstants, download_mmdet_retinanet_model, download_mmdet_config
from sahi.model import MmdetDetectionModel
from sahi.predict import get_sliced_prediction
from skimage.io import imread

# download retinanet weight
download_mmdet_retinanet_model()
# manually download retinanet configs under 'tests/data/models/mmdet_retinanet/'

# init detection model
detection_model = MmdetDetectionModel(
    model_path=MmdetTestConstants.MMDET_RETINANET_MODEL_PATH,
    config_path=MmdetTestConstants.MMDET_RETINANET_CONFIG_PATH,
    confidence_threshold=0.,
    device="cuda",
)

# perform inference
image_path = "20200618 MBBL Thermal Final_transparent_reflectance_grayscale_warped.tif"
image = imread(image_path)[:, :, 0:3].astype(np.uint8)
result = get_sliced_prediction(
    image,
    detection_model,
    slice_height=1024,
    slice_width=1024,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
)
```

Could you provide your model so that i can replicate your issue?

**Comment by abfleishman** [comment]
@fcakyon I have uploaded the models [here](https://drive.google.com/drive/folders/1yWlDAd54qqVF_1Ojrldx_Sel3RDmR1i1?usp=sharing) There are two folders `eseal_rgb_mask` and `eseal_rgb_cascade_mask` with the models I trained (They do not work all that well from what I can tell compared to the detectron2 mask rcnn i trained). I have also added the training data (`data_tiled_*` folders and the `labels_tiled_*.json` files) as well as the 4 full tif files (`data_rgbt`) that I would like to run sliced_prediciton on.
