### ISSUE TITLE
get_sliced_predictions fails when tiff is RGBA but model is only RGB

### ISSUE THREAD

**Issue by abfleishman** [obss/sahi#187]
I am 99% sure this is due to a mismatch in the number of channels the model expects and the number of channels in the image.  tiff files often have an "alpha" channel that is a boolean mask indicating where there is valid data.  I think that by default people often remove that channel in deep learning contexts.  I have images that are RGB+Thermal and thus will want to keep that channel once I figure out how to make a model that uses all 4 channels of info.  

I think having an argument that let you decide if the 4th channel should be removed or not would be useful.  Also FYI there is a package called `rasterio` that looks super useful for reading geospatial tiff data, but I have not figured out how to use it yet.  It has builtin functions for reading in windowed data from images to avoid putting the entire image in memory too.

```
# import required functions, classes
from sahi.model import MmdetDetectionModel
from sahi.predict import get_prediction, get_sliced_prediction, predict
from skimage.io import imread
import numpy as np

# #cascade
# model_path="/home/cmi/work_dirs/cascade_mask_rcnn_r50_fpn_1x_eseal_v2/epoch_100.pth"
# config_path="/home/cmi/work_dirs/cascade_mask_rcnn_r50_fpn_1x_eseal_v2/cascade_mask_rcnn_r50_fpn_1x_eseal_v2.py"

#mask
model_path="/home/cmi/work_dirs/mask_rcnn_r50_fpn_1x_coco_eseal_v1/epoch_200.pth"
config_path="/home/cmi/work_dirs/mask_rcnn_r50_fpn_1x_coco_eseal_v1/mask_rcnn_r50_fpn_1x_coco_eseal_v1.py"


# im_path="/home/cmi/eSeals/data_tiled_2048_png_rgb_nooverlap/20200224 FINAL_transparent_reflectance_grayscale_warped_4096_6144_6144_8192.png"
# im_path="/home/cmi/eSeals/data_tiled_1024_png_rgb_20overlap/20200224 FINAL_transparent_reflectance_grayscale_warped_2048_7168_3072_8192.png"
# im_path="/home/cmi/eSeals/data_tiled_1024_png_rgb_20overlap/20200403 Thermal FINAL_transparent_reflectance_grayscale_warped_5120_7168_6144_8192.png"
im_path="/home/cmi/eSeals/data/20200224 FINAL_transparent_reflectance_grayscale_warped.tif"
detection_model = MmdetDetectionModel(
    model_path=model_path,
    config_path=config_path,
    confidence_threshold=0.,
    device="cuda", # or 'cuda'
)

result = get_sliced_prediction(
    im_path,
    detection_model,
    slice_height = 1024,
    slice_width = 1024,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)

```

> Number of slices: 240
> Traceback (most recent call last):
> 
>   File "/tmp/ipykernel_6561/1363804212.py", line 7, in <module>
>     overlap_width_ratio = 0.2
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/predict.py", line 221, in get_sliced_prediction
>     slice_image_result.original_image_width,
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/predict.py", line 63, in get_prediction
>     detection_model.perform_inference(np.ascontiguousarray(image_as_pil), image_size=image_size)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/sahi/model.py", line 222, in perform_inference
>     prediction_result = inference_detector(self.model, image)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 129, in inference_detector
>     data = test_pipeline(data)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
>     data = t(data)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/test_time_aug.py", line 106, in __call__
>     data = self.transforms(_results)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
>     data = t(data)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/transforms.py", line 666, in __call__
>     self.to_rgb)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/photometric.py", line 21, in imnormalize
>     return imnormalize_(img, mean, std, to_rgb)
> 
>   File "/anaconda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/photometric.py", line 42, in imnormalize_
>     cv2.subtract(img, mean, img)  # inplace
> 
> error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

**Comment by fcakyon** [comment]
Lets continue the discussion here: https://github.com/obss/sahi/issues/186
