### ISSUE TITLE
an object is detected as two different classes

### ISSUE THREAD

**Issue by Grenaf** [obss/sahi#200]
Hello author, I am very happy to use your sliding window tool. But I encountered an object detected as a different class, how should I avoid this problem！
![image](https://user-images.githubusercontent.com/73221711/129681099-cb01634d-18a0-4e13-8530-006d2f4a9c35.png)

**Comment by fcakyon** [comment]
@Grenaf thanks a lot for your interest in the library!

## CLI
If you are using predict.py script in CLI, then add `--class_agnostic` arg as `python predict.py --class_agnostic`. Refer to scripts docs for more detail on other arguments: https://github.com/obss/sahi/blob/main/docs/SCRIPTS.md#predictpy-script-usage

## Python
If you are calling from python,
- set `postprocess_class_agnostic=True` when calling `predict` function: https://github.com/obss/sahi/blob/66550bda8590b2bf394dfc9b0a48390beb5369b7/sahi/predict.py#L287
- or set `postprocess_class_agnostic=True` when calling `get_sliced_prediction` function: https://github.com/obss/sahi/blob/66550bda8590b2bf394dfc9b0a48390beb5369b7/sahi/predict.py#L117

**Comment by Grenaf** [comment]
Thank you sir, nice tool. It works!
![image](https://user-images.githubusercontent.com/73221711/129692654-7e4048aa-4d6e-46f2-a687-5ade1bf2ed0f.png)

**Comment by fcakyon** [comment]
@Grenaf thanks a lot for your feedback! Feel free to open any issues or prs at any time :+1:
