### ISSUE TITLE
Can't export to coco format

### ISSUE THREAD

**Issue by aquexel** [obss/sahi#202]
Hello everybody

I'm trying to export result with your module, but I get this type of error. 
I know this problem came from shapely but there is a bug with the coordinates
How can I solve this ?

Thank you guys !

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.9/site-packages/shapely/speedups/_speedups.pyx in shapely.speedups._speedups.geos_linearring_from_py()

AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_784/2463133590.py in <module>
----> 1 result.to_coco_annotations()

/opt/conda/lib/python3.9/site-packages/sahi/prediction.py in to_coco_annotations(self)
    182         coco_annotation_list = []
    183         for object_prediction in self.object_prediction_list:
--> 184             coco_annotation_list.append(object_prediction.to_coco_prediction().json)
    185         return coco_annotation_list
    186 

/opt/conda/lib/python3.9/site-packages/sahi/prediction.py in to_coco_prediction(self, image_id)
    114         """
    115         if self.mask:
--> 116             coco_prediction = CocoPrediction.from_coco_segmentation(
    117                 segmentation=self.mask.to_coco_segmentation(),
    118                 category_id=self.category.id,

/opt/conda/lib/python3.9/site-packages/sahi/utils/coco.py in from_coco_segmentation(cls, segmentation, category_id, category_name, score, iscrowd, image_id)
    327                 0 or 1
    328         """
--> 329         return cls(
    330             segmentation=segmentation,
    331             category_id=category_id,

/opt/conda/lib/python3.9/site-packages/sahi/utils/coco.py in __init__(self, segmentation, bbox, category_id, category_name, image_id, score, iscrowd)
    421         """
    422         self.score = score
--> 423         super().__init__(
    424             segmentation=segmentation,
    425             bbox=bbox,

/opt/conda/lib/python3.9/site-packages/sahi/utils/coco.py in __init__(self, segmentation, bbox, category_id, category_name, image_id, iscrowd)
    195 
    196         if self._segmentation:
--> 197             shapely_annotation = ShapelyAnnotation.from_coco_segmentation(segmentation=self._segmentation)
    198         else:
    199             shapely_annotation = ShapelyAnnotation.from_coco_bbox(bbox=bbox)

/opt/conda/lib/python3.9/site-packages/sahi/utils/shapely.py in from_coco_segmentation(cls, segmentation, slice_bbox)
     66             Is used to calculate sliced coco coordinates.
     67         """
---> 68         shapely_multipolygon = get_shapely_multipolygon(segmentation)
     69         return cls(multipolygon=shapely_multipolygon, slice_bbox=slice_bbox)
     70 

/opt/conda/lib/python3.9/site-packages/sahi/utils/shapely.py in get_shapely_multipolygon(coco_segmentation)
     27     for coco_polygon in coco_segmentation:
     28         point_list = list(zip(coco_polygon[0::2], coco_polygon[1::2]))
---> 29         shapely_polygon = Polygon(point_list)
     30         polygon_list.append(shapely_polygon)
     31     shapely_multipolygon = MultiPolygon(polygon_list)

/opt/conda/lib/python3.9/site-packages/shapely/geometry/polygon.py in __init__(self, shell, holes)
    241 
    242         if shell is not None:
--> 243             ret = geos_polygon_from_py(shell, holes)
    244             if ret is not None:
    245                 self._geom, self._ndim = ret

/opt/conda/lib/python3.9/site-packages/shapely/geometry/polygon.py in geos_polygon_from_py(shell, holes)
    507 
    508     if shell is not None:
--> 509         ret = geos_linearring_from_py(shell)
    510         if ret is None:
    511             return None

/opt/conda/lib/python3.9/site-packages/shapely/speedups/_speedups.pyx in shapely.speedups._speedups.geos_linearring_from_py()

ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by fcakyon** [comment]
@aquexel could you share your coco.json so that i can recreate the issue and fix it? if its confidential could you at least copy a sample object annotation here?

The error is caused by 2 point segmentation annotation i assume but you have to confirm it.

**Comment by aquexel** [comment]
Hi,
What coco.json do you mean ? 
Maybe you're right, is it possible to remove this type of object ?
Thank you

**Comment by fcakyon** [comment]
@aquexel would you give the input image and model weight? If not, could you give some more info? :)

Are you using an instance segmentation model?
Are you using yolov5 or mmdetection based detector?
Are you performing sliced or standard inference?
What are the object sizes in the input image?
What is the input image resolution?

**Comment by fcakyon** [comment]
@aquexel can you tell me your working environment? Are you getting this error on one of the demo notebooks?

**Comment by aquexel** [comment]
I 'm using CBNetV2 for instance segmentation on big pictures. 
Here is my type of detection:
![image](https://user-images.githubusercontent.com/58343149/130517192-3c28be7d-ae37-48ae-9f7a-3eedc64b99f4.png)
I'm working with cuda 11.1

**Comment by aquexel** [comment]
def rletococo(file1,tol):
    for annotation in file1:
        d={}
        segmentation = []
        segmentation_polygons = []
        # Decodage RLE
        mask_list = mask_util.decode(annotation['segmentation'])   
        mask = np.ascontiguousarray(mask_list)
        contours, hierarchy = cv2.findContours((mask).astype("uint8"), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    # Obtention des contours
        if len(contours)>0 :
            for contour in contours:
                contour = contour.flatten().tolist()
                if len(contour)>=8:
                    segmentation.append(contour)

                    
    # Polygone
            if segmentation!=[]:
                for i, segment in enumerate(segmentation):
                    poligon = []
                    poligons = []
                    for j in range(len(segment)):
                        poligon.append(segment[j])
                        if (j+1)%2 == 0:
                            poligons.append(poligon)
                            poligon = []
                    inc=Polygon(poligons).area
                    d[inc]=poligons
                box_limit=np.asfortranarray(mask_list)
                box_limit2=mask_util.encode(box_limit)
                bbox = mask_util.toBbox(box_limit2)
                annotation['bbox']=bbox.tolist()
                annotation['segmentation'] = [d[max(d)]]
                segment=annotation['segmentation'][0]
                segment=np.array(segment)
                segment=segment.reshape(-1,2)
                poly=measure.approximate_polygon(segment, tol)
                segment=poly.tolist()
                if len(segment)>3:
                    annotation['segmentation']=[segment]
                else:
                    annotation['segmentation'] = {}
            else:
                annotation['segmentation'] = {}
        else:
            pass
    return file1

Here is my ancien code with detectron2 to do the same thing with your module
It's a bit archaique

**Comment by fcakyon** [comment]
@aquexel would you copy the code you are using with `sahi` that returns the error above?

**Comment by fcakyon** [comment]
@aquexel Could you try this at the end, instead of `result.to_coco_annotations()[0]` ?

```python
coco_annotation_list = []
for object_prediction in result .object_prediction_list:
    try:
        coco_annotation_list.append(object_prediction.to_coco_prediction().json)
    except:
        print(f"skipping this prediction: {object_prediction}")
```

**Comment by aquexel** [comment]
Thank you it works !

**Comment by fcakyon** [comment]
@aquexel glad to hear that! feel free to try all the features and ask again if you have any questions!
