### ISSUE TITLE
 raise Exception("Box coords [minx, miny, maxx, maxy] cannot be negative")

### ISSUE THREAD

**Issue by aquexel** [obss/sahi#203]
Hi everybody, I have got an another problem with the inference function. I've tried this code :
result = get_sliced_prediction(
    img,
    detection_model,
    slice_height = 1100,
    slice_width = 1100,
    overlap_height_ratio = 0.3,
    overlap_width_ratio = 0.3
)
The image is 14300x10400
How can I fix this ?

Thank you

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_714/1991668329.py in <module>
----> 1 result = get_sliced_prediction(
      2     img,
      3     detection_model,
      4     slice_height = 1100,
      5     slice_width = 1100,

/opt/conda/lib/python3.9/site-packages/sahi/predict.py in get_sliced_prediction(image, detection_model, image_size, slice_height, slice_width, overlap_height_ratio, overlap_width_ratio, perform_standard_pred, postprocess_type, postprocess_match_metric, postprocess_match_threshold, postprocess_class_agnostic, verbose)
    212             shift_amount_list.append(slice_image_result.starting_pixels[group_ind * num_batch + image_ind])
    213         # perform batch prediction
--> 214         prediction_result = get_prediction(
    215             image=image_list[0],
    216             detection_model=detection_model,

/opt/conda/lib/python3.9/site-packages/sahi/predict.py in get_prediction(image, detection_model, image_size, shift_amount, full_shape, postprocess, verbose)
     68     time_start = time.time()
     69     # works only with 1 batch
---> 70     detection_model.convert_original_predictions(
     71         shift_amount=shift_amount,
     72         full_shape=full_shape,

/opt/conda/lib/python3.9/site-packages/sahi/model.py in convert_original_predictions(self, shift_amount, full_shape)
    135                 Size of the full image after shifting, should be in the form of [height, width]
    136         """
--> 137         self._create_object_prediction_list_from_original_predictions(
    138             shift_amount=shift_amount,
    139             full_shape=full_shape,

/opt/conda/lib/python3.9/site-packages/sahi/model.py in _create_object_prediction_list_from_original_predictions(self, shift_amount, full_shape)
    295                 category_name = category_mapping[str(category_id)]
    296 
--> 297                 object_prediction = ObjectPrediction(
    298                     bbox=bbox,
    299                     category_id=category_id,

/opt/conda/lib/python3.9/site-packages/sahi/prediction.py in __init__(self, bbox, category_id, category_name, bool_mask, score, shift_amount, full_shape)
     73         """
     74         self.score = PredictionScore(score)
---> 75         super().__init__(
     76             bbox=bbox,
     77             category_id=category_id,

/opt/conda/lib/python3.9/site-packages/sahi/annotation.py in __init__(self, bbox, bool_mask, category_id, category_name, shift_amount, full_shape)
    547             )
    548             bbox = get_bbox_from_bool_mask(bool_mask)
--> 549             self.bbox = BoundingBox(bbox, shift_amount)
    550         category_name = category_name if category_name else str(category_id)
    551         self.category = Category(

/opt/conda/lib/python3.9/site-packages/sahi/annotation.py in __init__(self, box, shift_amount)
     30                 to full sized image, should be in the form of [shift_x, shift_y]
     31         """
---> 32         if box[0] < 0 or box[1] < 0 or box[2] < 0 or box[3] < 0:
     33             raise Exception("Box coords [minx, miny, maxx, maxy] cannot be negative")
     34         self.minx = int(box[0])

IndexError: list index out of range

**Comment by fcakyon** [comment]
@aquexel i have just released a new version: https://github.com/obss/sahi/releases/tag/0.7.4 would you update and try again with `pip install -U sahi` ?

Error seems to be caused by negative bounding box coords, do you have any idea why model results in negative bounding box values? Could you upload the raw input image so that i can recreate the issue?

**Comment by aquexel** [comment]
I let you my image
https://github.com/aquexel/aquexel

**Comment by Fetulhak** [comment]
@aquexel the problem is not in the sahi tool. if you are using yolov3 or v4 some of the predicted values for bbox are incorrectly calculated especially in image boarders.
