### ISSUE TITLE
How to cut the original image into the training network and export silce’s image and label

### ISSUE THREAD

**Issue by Grenaf** [obss/sahi#206]
Hi fackyon！I have some problems about getting  slices‘s images and labels.
# Material
- I have some personal original images(Resolution greater than 640x640) and their labels(yolov5 format)，but i want to send slices into yolov5 training network.
# Question
- I know there are two ways to cut the original image into the training network
  - slice the whole dataset and use the sliced images/annotations during training: https://github.com/obss/sahi/blob/main/scripts/slice_coco.py   but this way’s interface is "coco_json_path" 
  - For online cutting training and detection can be improve ultralytics/yolov5#3942，this is a online way, I do not know how to use this way 
- Is there any way to export slice images and their labels(yolov5 format) into a directory from original images？

**Comment by fcakyon** [comment]
Unfortunately only coco format is supported as the input format. You can something like this to convert your annotations into coco format: https://github.com/Taeyoung96/Yolo-to-COCO-format-converter

**Comment by Fetulhak** [comment]
Hi @ Grenaf  first convert your yolo annotation to coco annotation format using the tool suggested by @fcakyon. Then you will get the sliced images and their sliced coco annotation using SAHI tool. After that you should have to convert back again the sliced coco annotation back to yolo annotation using https://github.com/ssaru/convert2Yolo tool.

**Comment by Grenaf** [comment]
Thanks  Fetulhak and fcakyon！Infact fackyon has gived a way in tutorial to convert coco dataset to yolo，it is useful. 
![image](https://user-images.githubusercontent.com/73221711/131208722-59eb27ec-c630-4240-9e69-85cf052e0403.png)
# question
I have an immature question about using https://github.com/obss/sahi/blob/main/scripts/slice_coco.py I give default parameter but there is an error error: the following arguments are required: coco_json_path, coco_image_dir
![image](https://user-images.githubusercontent.com/73221711/131208893-965aa541-bcf5-446b-9f0c-93330e6f9770.png)
At last i slove it with pycharm terminal。python 1.py --ignore_negative_samples  E:\\Yolo-to-COCO-format-converter-master\\output\\train.json E:\\Yolo-to-COCO-format-converter-master\\mydataset\\images\\train

**Comment by Fetulhak** [comment]
@Grenaf just add \\ at the end of the image path:  "E:\Yolo-to-COCO-format-converter-master\mydataset\images\train\\"

**Comment by fcakyon** [comment]
@Fetulhak thanks a lot for your helps!

@Grenaf i see you have solved the issue, right?

**Comment by Grenaf** [comment]
There is something in second question。yolov5 requires Class numbers are zero-indexed (start from 0)，I have a total of 6 classes, the class numbers are from 1-6 when i use your tool（Convert COCO dataset to ultralytics/yolov5 format in tutorial）。I will try  
Fetulhak‘s way later

**Comment by fcakyon** [comment]
@Grenaf you have to fix your COCO categories first. You can use such script for that purpose:
```python
from sahi.utils.coco import Coco

remapping_dict={1:0, 2:1, 3:2, 4:3, 5:4, 6:5}
coco = Coco.from_coco_dict_or_path("coco.json", image_dir="dir/to/images", remapping_dict=remapping_dict)
```

then you can convert yo yolov5 format:
```python
coco.export_as_yolov5(output_dir="output/folder/dir", train_split_rate=0.85)
```
