### ISSUE TITLE
Add split to sahi?

### ISSUE THREAD

**Issue by abfleishman** [obss/sahi#213]
Often when creating a new dataset (using sahi to create slices on a larger image) users will want to split the new dataset into training, validation, and test datasets.  This is a little more complex when you are making overlapping slices.  Because of the overlap, the same part of the original image could end up in both training and test datasets even though the images are separate.  It could be nice to put some thought into how a train/test/val split could be made with sahi images, and have code to implement it in sahi.  I would be curious if @fcakyon or others have thought about this?  

I think this is a larger issue for me because I am working with only a few large images so I am no interested in holding out an entire image for test/val. but for others, keeping a set of original images separate for the test/val is probably a good option.

**Comment by fcakyon** [comment]
@abfleishman thanks a lot for your interest in the library!

You can split your coco formatted dataset into train/val as:

```python
from sahi.utils.coco import Coco

# specify coco dataset path
coco_path = "coco.json"

# init Coco object
coco = Coco.from_coco_dict_or_path(coco_path)

# split COCO dataset with a 85% train/15% val split
result = coco.split_coco_as_train_val(
  train_split_rate=0.85
)

# export train val split files
save_json(result["train_coco"].json, "train_split.json")
save_json(result["val_coco"].json, "val_split.json")
```

then run `sahi coco slice` command for splitted coco sets as:

```bash
sahi coco slice --image_dir dir/to/images --dataset_json_path train_split.json --slice_size 512 --overlap_ratio 0.2
```

```bash
sahi coco slice --image_dir dir/to/images --dataset_json_path val_split.json --slice_size 512 --overlap_ratio 0.2
```

and sliced training/validation images & annotations will be exported under `runs/slice_coco/`

**Comment by fcakyon** [comment]
For all COCO utility function details, refer to: https://github.com/obss/sahi/blob/main/docs/COCO.md
For all `sahi` CLI details, refer to: https://github.com/obss/sahi/blob/main/docs/CLI.md

**Comment by fcakyon** [comment]
@abfleishman I just realized your concern, currently creating train/val splits from a single image is not supported. But since the order of splits are preserved, you can spare the latest %10 images from coco annotation file for validation (set `overlap_ratio` as `0`).

**Comment by fcakyon** [comment]
Closing the issue now, if you have any questions would gladly open it back :+1:
