### ISSUE TITLE
postprocess_type and postproces_match_metrics

### ISSUE THREAD

**Issue by Fetulhak** [obss/sahi#214]
@fcakyon in most object detection tasks the IOU threshold and NMS are used to get the final prediction result. While you have setted the default values for these parameters as IOS and UNIONMEGE. are these parameters the most optimal in terms of performance?

**Comment by fcakyon** [comment]
@Fetulhak for dense scenarios (50+ objects in frame as in visdrone-det dataset) and in similar target classes (tri-cycle/bi-cycle/motor as in visdrone-det dataset) IOU+NMS perform better but we have seen that in less crowded frames and distinct target classes (car/pedestrian/truck), IOS+UNIONMERGE perform better.

- You can use [`sahi predict`](https://github.com/obss/sahi/blob/main/docs/CLI.md#predict-command-usage) to get prediction on your coco formatted validation set and save the result in coco result format.
- Then use [`sahi coco evaluate`](https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-evaluate-command-usage) to evaluate the performance. Then compare the results of different postprocessing parameters and select the best one fitting to your problem.
- You can also compare the predictions of different post process parameters visually with [`sahi coco fiftyone`](https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-fiftyone-command-usage).

**Comment by Grenaf** [comment]
It can be known that the IOU+NMS algorithm can remove duplicate bounding boxes of the same category,    postprocess_class_agnostic: bool，If True, postprocess will ignore category ids.https://github.com/obss/sahi/issues/200#issuecomment-900069625 When using the IOS+UNIONMERGE algorithm, you ignore the id, so it is still a single-category object that is judged in the end？

**Comment by fcakyon** [comment]
IOU+NMS and IOS+UNIONMERGE works exactly same in terms of category ids.
If `postprocess_class_agnostic=True`, postprocess ignores category ids, else cross-category merging is not performed.

Comment again if you think my comment is not clear.

**Comment by Fetulhak** [comment]
Hi @fcakyon may be I am mistaken but in the following code snippet under postproces.combine isn't it wrong to use the "if not self._has_match" and rather to use "if  self._has_match" . since based on the principles of NMS we should remove duplicate boxes with higher match than the threshold value

for candidate_object_prediction in source_object_predictions:
                if not self._has_match(selected_object_prediction, candidate_object_prediction):

**Comment by fcakyon** [comment]
> Hi @fcakyon may be I am mistaken but in the following code snippet under postproces.combine isn't it wrong to use the "if not self._has_match" and rather to use "if self._has_match" . since based on the principles of NMS we should remove duplicate boxes with higher match than the threshold value
> 
> this is in class NMSPostprocess(PostprocessPredictions):
> 
> ```
> for candidate_object_prediction in source_object_predictions:
>                 if not self._has_match(selected_object_prediction, candidate_object_prediction):
> ```

Thanks a lot for pointing that out, your are right on that, opened a pr regarding it: https://github.com/obss/sahi/pull/287
