### ISSUE TITLE
Can I add different color bounding boxes and text for different classes when use visualize_object_predictions？

### ISSUE THREAD

**Issue by Grenaf** [obss/sahi#216]
When synthesizing the prediction result of the picture, I can adjust the color and annotate the text first. I found these annotation codes，
https://github.com/obss/sahi/blob/97459f8a221d25b91490a6a6399323e0c0933db6/sahi/utils/cv.py#L238-L261
https://github.com/obss/sahi/blob/97459f8a221d25b91490a6a6399323e0c0933db6/sahi/predict.py#L105-L126
# question
* Can I add different color bounding boxes and text for different classes when use visualize_object_predictions？
* Can get_sliced_prediction be used to detect all pictures in a directory at a time？

**Comment by fcakyon** [comment]
@Grenaf you can use [`sahi predict`](https://github.com/obss/sahi/blob/main/docs/CLI.md#predict-command-usage) script to perform sliced prediction to all pictures in a directory in one go.

**Comment by fcakyon** [comment]
For classwise box color, i will work on a update when i find some time, cannot give you an ETA unfortunately :)

We are open to any PR by the way :100:

**Comment by fcakyon** [comment]
@Grenaf this feature has been implemented by the way :) check this pr: https://github.com/obss/sahi/pull/271

**Comment by Grenaf** [comment]
> @Grenaf this feature has been implemented by the way :) check this pr: #271

OK I see，good！I have used this function。
