### ISSUE TITLE
handle when abs path is provided in coco_image for merging

### ISSUE THREAD

**Issue by fcakyon** [obss/sahi#229]
image dir should not be required when coco_image path is absolute: https://github.com/obss/sahi/blob/b28284380be0aabe4076d3835f67e51b059eefc6/sahi/utils/coco.py#L875

**Comment by devrimcavusoglu** [comment]
isn't this case here for otherwise (for paths that aren't absolute) ?

```python
if update_image_filenames and not file_name_is_abspath:
    updated_coco_image.file_name = str(Path(os.path.abspath(self.image_dir)) / coco_image.file_name)
```

**Comment by fcakyon** [comment]
@devrimcavusoglu yes you are right, currently this check is causing errors. it fails even if the image paths are abolute: https://github.com/obss/sahi/blob/b28284380be0aabe4076d3835f67e51b059eefc6/sahi/utils/coco.py#L904
