### ISSUE TITLE
where i can set maximum detection per image?

### ISSUE THREAD

**Issue by Guttappa1238** [obss/sahi#232]
Hi,

i have more than 1000 objects in a image but i'm getting only 1000 objects detected image. how can i set `max_det`  ?

**Comment by fcakyon** [comment]
@Guttappa1238 thanks a lot for using SAHI!

Would you mind giving some more info so that we can help you better?
- What is your `model_type`? (yolov5 or mmdet)
- What is your prediction type? (sliced or standard)
- What is your inference image size and slice size?
- Are you using CLI or doing a function call?

Would be great if you could share your inference code snippet.

**Comment by Guttappa1238** [comment]
> @Guttappa1238 thanks a lot for using SAHI!
> 
> Would you mind giving some more info so that we can help you better?
> 
> * What is your `model_type`? (yolov5 or mmdet)
> * What is your prediction type? (sliced or standard)
> * What is your inference image size and slice size?
> * Are you using CLI or doing a function call?
> 
> Would be great if you could share your inference code snippet.

Thanks for quick response,

1. `model_type` : yolov5
2. prediction type : tried both standard and sliced
3. `image_size` : 1280 (trained yolov5 with `--img_size` 1280)
4. doing function call
here is the snippet

```
detection_model = Yolov5DetectionModel(
    model_path=yolov5_model_path,
    confidence_threshold=0.3,
    device="cuda", # or 'cuda'
)
```

**Comment by fcakyon** [comment]
@Guttappa1238 you have to change `max_det` value of the yolov5 model: https://github.com/fcakyon/yolov5-pip/blob/5324365eacdf6cd58cfc37cc133bbc344f1922be/yolov5/models/common.py#L280

```python
# init yolov5 detection model
detection_model = Yolov5DetectionModel(
    model_path=yolov5_model_path,
    confidence_threshold=0.3,
    device="cuda:0",
)

# increase max_det value of yolov5 model (default is 1000)
detection_model.model.max_det = 3000

# perform inference
result = get_sliced_prediction(
    image_path,
    detection_model,
    image_size = 1280,
    slice_height = 512,
    slice_width = 512,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)

# export visuals
result.export_visuals(export_dir="result/")
```

Closing the issue for now, feel free to write again if you have any questions!
