### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aquexel** [obss/sahi#235]
Hi,
For an inference with an overlap of 0.2 it works, but for 0.3 it doesn't work
Why I get this error ?

Thank you !

```python
Traceback (most recent call last):
  File "/project_antwerp/inference.py", line 15, in <module>
    result = get_sliced_prediction(
  File "/opt/conda/lib/python3.9/site-packages/sahi/predict.py", line 214, in get_sliced_prediction
    prediction_result = get_prediction(
  File "/opt/conda/lib/python3.9/site-packages/sahi/predict.py", line 70, in get_prediction
    detection_model.convert_original_predictions(
  File "/opt/conda/lib/python3.9/site-packages/sahi/model.py", line 137, in convert_original_predictions
    self._create_object_prediction_list_from_original_predictions(
  File "/opt/conda/lib/python3.9/site-packages/sahi/model.py", line 310, in _create_object_prediction_list_from_original_predictions
    object_prediction = ObjectPrediction(
  File "/opt/conda/lib/python3.9/site-packages/sahi/prediction.py", line 75, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.9/site-packages/sahi/annotation.py", line 549, in __init__
    self.bbox = BoundingBox(bbox, shift_amount)
  File "/opt/conda/lib/python3.9/site-packages/sahi/annotation.py", line 32, in __init__
    if box[0] < 0 or box[1] < 0 or box[2] < 0 or box[3] < 0:
IndexError: list index out of range
```

**Comment by fcakyon** [comment]
@aquexel thanks a lot for your submission!

Would you mind sharing the sample image and weight file so that we can recreate your issue?

**Comment by fcakyon** [comment]
> Hi, I think have the exact same error. for some models, parameters, and images, it went well but for some of the others, it threw an error. I didnt find any pattern on what might cause the error.
> 
> **Error** [1] models: https://drive.google.com/file/d/1Wh5pS3vj64DhqgdhZO0H06CCCe2Lptes 【epoch_100scratch.pth】 function used: `get_prediction` params: model's confidence_threshold = 0.4 image: https://drive.google.com/file/d/1mSI6VQ2cGCaoyvbTQXVnv-JZUkKwjDXk 【no04b_03.png】 [2] models: https://drive.google.com/file/d/1Wh5pS3vj64DhqgdhZO0H06CCCe2Lptes 【epoch_100scratch.pth】 function used: `get_slice_prediction` params: model's confidence_threshold = 0.4 slice_height = 128, slice_width = 128, overlap_height_ratio = 0.3, overlap_width_ratio = 0.3 image: https://drive.google.com/file/d/1-swlREgdivj_GvYyi-6jAB8ZN-7wUeRs 【Screenshot 2021-10-06 163117.jpg】
> 
> **Not Error** [1] models: https://drive.google.com/file/d/1osMIAP81yw1jfsmA9DjlZ3kUQZiTbVGJ 【epoch_100.pth】 function used: `get_prediction` params: model's confidence_threshold = 0.4 image: https://drive.google.com/file/d/1mSI6VQ2cGCaoyvbTQXVnv-JZUkKwjDXk 【no04b_03.png】 [2] models: https://drive.google.com/file/d/1Wh5pS3vj64DhqgdhZO0H06CCCe2Lptes 【epoch_100scratch.pth】 function used: `get_slice_prediction` params: model's confidence_threshold = 0.4 slice_height = 256, slice_width = 256, overlap_height_ratio = 0.2, overlap_width_ratio = 0.2 image: https://drive.google.com/file/d/1-swlREgdivj_GvYyi-6jAB8ZN-7wUeRs 【Screenshot 2021-10-06 163117.jpg】
> 
> Note: prediction was performed using CPU.

Sorry for the late reply, I cannot recreate the error using your data. What is the model type of your provided weight here? YoloV5 or MMDetection? It seems to be a MMDetection model but you did not provide a config.py which is necessary for all MMDetection models.

If you could help me recreate this error I will fix it in 1-2 days :+1:
