### ISSUE TITLE
How can I get predicted image and save image ?

### ISSUE THREAD

**Issue by MdRanaSarkar** [obss/sahi#260]
I've used this command for predicted . In my site everything works successfully . But one problem . Here predicted images not save . How can I save predicted images  or How can get predicted images ? 
sahi predict --slice_width 256 --slice_height 256 --overlap_height_ratio 0.1 --overlap_width_ratio 0.1 --model_confidence_threshold 0.25 --source image/file/or/folder --model_path path/to/model --model_config_path path/to/config

**Comment by fcakyon** [comment]
Thanks a lot for your interest in SAHI @MdRanaSarkar !

You have to add `--export_visual` argument to export visuals.

Here you can see details on all of the arguments: https://github.com/obss/sahi/blob/main/docs/CLI.md#predict-command-usage
