### ISSUE TITLE
faster nms implementation

### ISSUE THREAD

**Issue by fanweiya** [obss/sahi#263]
I used sahi to cut the image and count the cells.this is [image.](https://kdocs.cn/l/sak4HJobioT8),But sahi spent a lot of time in postprocessing, and this kind of image took about ten Minutes.

this my code.
```
from sahi.model import Yolov5DetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict
from imutils.paths import list_images
imgpath="test.jpg"
detection_model = Yolov5DetectionModel(
    model_path="best.pt",
    confidence_threshold=0.1,
    device="cuda", # or 'cuda'
)
result = get_sliced_prediction(
    imgpath,
    detection_model,
    slice_height=1024,
    slice_width=1024,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
)
result.export_visuals(export_dir=r"H:\test")
```

**Comment by fcakyon** [comment]
@fanweiya when the number of proposals is very large, it is expected from postprocess to take long. You can increase the confidence threshold for faster postprocessing.

**Comment by fanweiya** [comment]
you can use https://github.com/remydubois/lsnms

**Comment by fcakyon** [comment]
@fanweiya thanks for your feedback! It is now in our roadmap but no ETA. We are open to any PR!

**Comment by phborba** [comment]
Hi, @fcakyon, how are you doing? First of all, congrats on the framework! It is fantastic! Are you guys interested in putting the lsnms that @fanweiya suggested? If you guys are willing to integrate it, maybe I could do it for you. What do you think?

**Comment by fcakyon** [comment]
@phborba i am happy to hear your nice words on the framework!

If you are willing to implement lsnms into `sahi`, we are open to accept your PR!

What you have to do is to add a new class named `LSNMSPostprocess` similar to our current [NMSPostprocess class](https://github.com/obss/sahi/blob/21ecb285aa6bf93c2a00605dfb9b138f19d8d62d/sahi/postprocess/combine.py#L103).

**Comment by remydubois** [comment]
Hey, I am the developer of the `lsnms` library.
If you guys @phborba @fcakyon need help in integrating `lsnms.nms` into `sahi`, feel free to tag me in this thread.  

Cheers

**Comment by fanweiya** [comment]
lsnms is fast, but How do I quickly make Numba warmup?

**Comment by remydubois** [comment]
To curb compilation time overhead, Numba implements a compiler cache (allowing to compile once and for all, per machine), which, unfortunately, does not work with recursive functions (which is used in `lsnms.nms`).  
I know that they have been trying to solve the issue [(cf this issue)](https://github.com/numba/numba/issues/6713#issue-804901574) but it is still pending as of now.

I fear that until it is solved on Numba's side, `lsnms.nms` is stuck with this compilation overhead.
