### ISSUE TITLE
Sahi inference uses RGB chanel order versus mmdetection uses BGR chanel order

### ISSUE THREAD

**Issue by tureckova** [obss/sahi#265]
While tracking down the error with Sahi slice prediction resulting in different output than mmdetection inference on some single slice of the image (mentioned in [issue](https://github.com/obss/sahi/issues/239#issuecomment-950621569) about test_pipeline in mmdetection), I found the error was due to the different order of the image color channels.

While you use the RGB channel order, the mmdetection loads images in the BGR channel order. I use the .jpeg image format as input.

You can debug how the image array actually looks by calling inference_detector with img_path instead of numpy array:
```
# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cpu')
# test a single image and show the results
result = inference_detector(model, img_path)
```
or can replicate just the part of mmdetection class [LoadImageFromFile](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/loading.py)
```
file_client = mmcv.FileClient(None)
img_bytes = file_client.get(img_path)
img = mmcv.imfrombytes(img_bytes, flag='color')
```
In both cases, the loaded np.array featured the image in BGR order.

Unlike your function read_image:
```
image = read_image(img_path)
```
which results in RGB channel ordering.

**Comment by fcakyon** [comment]
@tureckova thanks a lot for your valuable contributions! So we need to give BGR input for mmdetection backend and RGB input for yolov5 backend. Will work on a fix when I find some time!

**Comment by fcakyon** [comment]
@tureckova it is fixed in the latest release. Thanks a lot for your contribution!
