### ISSUE TITLE
Detect small and large targets at the same time using `sahi`?

### ISSUE THREAD

**Issue by Grenaf** [obss/sahi#274]
When I use sahi for object detection, some new ideas will always appear in my mind！If I use slice inference to detect small targets, then large targets will be split. What should I do if this happens? Like this situation，if I set slice 640x640！
![image](https://user-images.githubusercontent.com/73221711/142184501-12693edc-ced7-4f33-a566-840bbb8ee648.png)

**Comment by fcakyon** [comment]
@Grenaf that's a great question!

By default, `sahi predict` applies both **sliced** and **standard** inference and merges the results. That should solve your issue since the larger objects will be detected by **standard inference** and the smaller ones will be detected by **sliced inference**!

**Comment by fcakyon** [comment]
By the way this blog summarizes the remote sensing application of `sahi`. You can check it if you haven't seen already! https://blog.ml6.eu/how-to-detect-small-objects-in-very-large-images-70234bab0f98

**Comment by Grenaf** [comment]
> By the way this blog summarizes the remote sensing application of `sahi`. You can check it if you haven't seen already! https://blog.ml6.eu/how-to-detect-small-objects-in-very-large-images-70234bab0f98

* Thank you for your recommended website information. The blogger of the website is also doing small target detection.Their data set pixels range from 800x800 to 20000x20000。
* They also encountered a problem, usually the input image is scaled to a fairly small size, such as (1333,800), so a lot of information is lost.They used the method mentioned in the picture below。
![image](https://user-images.githubusercontent.com/73221711/142341261-a848f48a-3f1b-4ea5-8ac9-eb3b4ac08376.png)
![image](https://user-images.githubusercontent.com/73221711/142341780-6bdaf737-fcbb-4369-891e-cd7ef0426b10.png)
# question
If I want to detect small targets and large targets on my own high-resolution images at the same time, I need to add the original high-resolution images and slice images of the original high-resolution images during the network training phase. Is my idea correct? If I only add sliced images for training, it will not be able to detect large targets, and if I only add high-resolution images, such small targets will not be detected, right?

**Comment by fcakyon** [comment]
> * So you combine get_prediction (used for regular Inference) and get_sliced_prediction (used for sliced Inference) in the predict function.

Thats correct!

**Comment by fcakyon** [comment]
> If I want to detect small targets and large targets on my own high-resolution images at the same time, I need to add the original high-resolution images and slice images of the original high-resolution images during the network training phase. Is my idea correct? If I only add sliced images for training, it will not be able to detect large targets, and if I only add high-resolution images, such small targets will not be detected, right?

Yes you have to use both sliced images and full images in the training 👍

**Comment by fcakyon** [comment]
@Grenaf feel free to close this issue when you dont have any questions, you can open again in the future!

**Comment by Grenaf** [comment]
> @Grenaf feel free to close this issue when you dont have any questions, you can open again in the future!

OK，thanks！

**Comment by fcakyon** [comment]
@Grenaf new version `0.9.0` is live, update your `sahi` with `pip install -U sahi` 🚀 

https://github.com/obss/sahi/releases/tag/0.9.0
