### ISSUE TITLE
Question: plans for generic TorchVision models?

### ISSUE THREAD

**Issue by phborba** [obss/sahi#275]
Hi guys, how are you doing? First of all, congratulations on your work, it is incredible. Are you guys interested in integrating torchvision models? If you are, maybe I could do that for you. I am integrating your framework into mine, https://github.com/phborba/pytorch_segmentation_models_trainer, and it would be interesting if the torchvision models were included in sahi.

Please let me know if I can send a pull request!

**Comment by fcakyon** [comment]
Thanks a lot for your interest in SAHI @phborba!

If torchvision models have a common output api then we can implement a TorchvisionDetectionModel class that inherits from [DetectionModel class](https://github.com/obss/sahi/blob/21ecb285aa6bf93c2a00605dfb9b138f19d8d62d/sahi/model.py#L21).

If you could help on that, would be awesome!

**Comment by phborba** [comment]
Great! I'll start right away!

I was looking at the code, and I've got some questions:

1- I've noticed that [DetectionModel class](https://github.com/obss/sahi/blob/21ecb285aa6bf93c2a00605dfb9b138f19d8d62d/sahi/model.py#L21) only accepts configs. Are you willing to make it more generic so that it can also get pre-loaded models?

2- In my framework, I use hydra to instantiate configs. Are you interested in adding the option of reading hydra configs in DetectionModel class?

**Comment by fcakyon** [comment]
> 1- I've noticed that [DetectionModel class](https://github.com/obss/sahi/blob/21ecb285aa6bf93c2a00605dfb9b138f19d8d62d/sahi/model.py#L21) only accepts configs. Are you willing to make it more generic so that it can also get pre-loaded models?

What do you mean by `getting pre-loaded models`? Model loading should be implemented for your DetectionModel class but if you dont want to use it in your use case you can manually set the [model property](https://github.com/obss/sahi/blob/21ecb285aa6bf93c2a00605dfb9b138f19d8d62d/sahi/model.py#L197) with your pre-loaded model, it is up to you 👍

**Comment by fcakyon** [comment]
> 2- In my framework, I use hydra to instantiate configs. Are you interested in adding the option of reading hydra configs in DetectionModel class?

We cannot force the sahi users to use hydra configs for torchvision models in general. You should implement `TorchvisionDetectionModel` class so that it accepts standard python type variables (int float str etc) as the inputs. Conversion from hydra config to sahi inputs should be handled in your framework.

**Comment by phborba** [comment]
Great! Thanks for the guidelines! I'll start working on it!
