### ISSUE TITLE
kendi egittigim yolov5 modelini `sahi` ile kullanmak

### ISSUE THREAD

**Issue by kadirnar** [obss/sahi#276]
Merhabalar,

Pip üzerinden yolov5s modeli ile kendi veri setinde eğitim ve test aldım. Fakat sahi algoritmasını entegre ederken sıkıntı yaşadım. Kodun tamamı:

```python
yolov5_model_path = 'models/last.pt'
detection_model = Yolov5DetectionModel(
    model_path=yolov5_model_path,
    confidence_threshold=0.3,
    device="cuda")

result = get_sliced_prediction(
    "images/2.jpg",
    detection_model,
    slice_height = 256,
    slice_width = 256,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)

result.export_visuals(export_dir="demo_data/")
```

Bu kodu çalıştırdığımda resmin aynısını çıktı olarak veriyor. Console de şu uyarı mesajı alıyorum.

```bash
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Number of slices: 24
```

Açıkcası bununla ilgili blog,colab ve kendi github sayfasında çok arama yaptım fakat bilgi bulamadım. Yardımcı olabilir misiniz?

**Comment by fcakyon** [comment]
Merhaba @kadirnar, `sahi`ye olan ilginden ve sorun bildirimden dolayi cok tesekkurler!

Oncelikle bu hatayi aldigin ortamdaki sahi, torch ve yolov5 versiyonlarini bildirebilir misin?

Bir de hangi ortamda test ettin bu kod parcasini? Windows/Linux? Lokalinde mi yoksa Colab'de mi?

Verecegin bilgilere gore en kisa surede bir cozum bulmak isterim 👍

**Comment by fcakyon** [comment]
> ```shell
> UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> 
> Number of slices: 24
> ```

@kadirnar bu arada hata vermeden sorunsuz bir sekilde calismis script. Model obje tespiti yapamamis olabilir mi?

Girdi olarak verdigin goruntunun boyutlari kaca kac?

Girdi olarak verdigin goruntudeki objelerin buyuklukleri yaklasik kac piksel?

**Comment by fcakyon** [comment]
> 
> ```python
> yolov5_model_path = 'models/last.pt'
> detection_model = Yolov5DetectionModel(
>     model_path=yolov5_model_path,
>     confidence_threshold=0.3,
>     device="cuda")
> 
> result = get_sliced_prediction(
>     "images/2.jpg",
>     detection_model,
>     slice_height = 256,
>     slice_width = 256,
>     overlap_height_ratio = 0.2,
>     overlap_width_ratio = 0.2
> )
> 

Bu paremetrelerle sliced prediction yapmak, girdi olan goruntuyu 256*256'lik kesitlere bolup + 640 girdi boyutuna interpolate edip + yolov5 modeline girdi olarak vermeye denk geliyor.

Egittigin yolov5s modelini slice edilmemis bir egitim setiyle egittiysen ya da farkli girdi buyuklugunde egittiysen, parametrelerle biraz oynamak gerekecektir.

Onceki postlardaki sorularima cevap verebilirsen adim adim ilerleyerek tespit edelim sorunu 👍

**Comment by kadirnar** [comment]
Merhaba @fcakyon Hocam,

**Versiyonlar:** 

Yolov5: 6.0.4 
Pytorch: 1.10.0
Sahi: 0.8.8
Spyder: 5.1.5
Windows Local

Yaptığım işlemler çok basit. İlk önce iki nesneli bir sınıfı imgs=640 boyunda ve 10 epoch değerinde eğittim. Test ettiğimde nesneleri tanıyordu. Bende direk sahi algoritmasında denemek istedim. Yolov5s6 yerine kendi modeli koydum. Özel bir işlem yapmadım.

Test ettiğimdeki sonuçları github paylaştım. (https://github.com/kadirnar/yolov5-pytorch) 

**Colab üzerinde test etmek istediğimde ise şu hatayı aldım:**

AttributeError: 'NoneType' object has no attribute 'names'

**Hata mesajını verdiğii kod parçacığı ise:**

yolov5_model_path = '/runs/train/exp2/weights/best.pt'
detection_model = Yolov5DetectionModel(
    model_path=yolov5_model_path,
    confidence_threshold=0.3,
    device="cuda")

**Comment by kadirnar** [comment]
@fcakyon Hocam,

 confidence_threshold=0.1 değerini küçültmek işe yaradı diyebilirim. Fakat başarı oranını düşürdü diyebilirim. 
 
 Pip üzerinden predict yaptığımda:

![output1](https://user-images.githubusercontent.com/36204372/142500461-a18e2638-798e-4e95-9ab9-7511fcece0df.jpg)

Yolov5DetectionModel fonksiyonu kullanarak predict yaptığımda:

![prediction_visual](https://user-images.githubusercontent.com/36204372/142500608-7add7aad-56e8-415e-96c3-5eac05275a53.png)

Sahi Algoritması Kullandığımda:

![prediction_visual](https://user-images.githubusercontent.com/36204372/142500842-4a45078b-7ad7-4fc7-93d7-2f6fd5bb6593.png)

Sahi algoritması istediğim sonuçları vermiyor. Parametre değerleri ile oynadığımda tespit ettiği sonuçları artırabiliyorum. Fakat uzakttaki nesnelerin tespitinde halen eksik diyelim. Modeli 10 epoch ile eğittim için uzakta nesneleri tespit edemiyor demek daha doğru olacak galiba.

Fakat pip ile Yolov5DetectionModel arasında neden bu kadar fark oluyor onu anlayamadım. Ne tarz parametre ayarları ile oynamamız gerekiyor? Sahi algoritmasını daha verimli kullanmak için bir readme.md güzel olabilir hocam.

**Comment by fcakyon** [comment]
@kadirnar bilgiler icin cok tesekkurler.

Oncelikle sahi versiyonunu `pip install -U sahi` diyerek son surume guncelleyebilir misin? Bircok bugfix geldi [v0.8.9](https://github.com/obss/sahi/releases/tag/0.8.9) ile birlikte :)

Sonrasinda bu sekilde sliced olmayan standard prediction almayi deneyip nasil output verdigini bildirebilir misin?

 ```python
from sahi.model import Yolov5DetectionModel
from sahi.predict import get_prediction

detection_model = Yolov5DetectionModel(
    model_path="/runs/train/exp2/weights/best.pt'",
    confidence_threshold=0.25,
    device="cuda:0",
)

result = get_prediction("images/2.jpg", detection_model)

result.export_visuals(export_dir="demo_data/")
```

**Comment by fcakyon** [comment]
> **Colab üzerinde test etmek istediğimde ise şu hatayı aldım:**
> 
> AttributeError: 'NoneType' object has no attribute 'names'
> 
> **Hata mesajını verdiğii kod parçacığı ise:**
> 
> yolov5_model_path = '/runs/train/exp2/weights/best.pt' detection_model = Yolov5DetectionModel( model_path=yolov5_model_path, confidence_threshold=0.3, device="cuda")

@kadirnar bu hata modelin path'inin yanlis verildigini ve modeli yukleyemedigini gosteriyor.

Colab'de dosya path'leri genelde `content/` ile baslar, senin yazdigin root dizin olan `/runs`in gercekten mevcut oldugundan emin misin? Dogrusu `runs` seklinde bir relative path olabilir mi?

**Comment by fcakyon** [comment]
@kadirnar bu arada weight dosyasini upload edip drive linki verebilirsen daha hizli tespit edebilirim sorunun kaynagini 👍

**Comment by kadirnar** [comment]
> > **Colab üzerinde test etmek istediğimde ise şu hatayı aldım:**
> > AttributeError: 'NoneType' object has no attribute 'names'
> > **Hata mesajını verdiğii kod parçacığı ise:**
> > yolov5_model_path = '/runs/train/exp2/weights/best.pt' detection_model = Yolov5DetectionModel( model_path=yolov5_model_path, confidence_threshold=0.3, device="cuda")
> 
> @kadirnar bu hata modelin path'inin yanlis verildigini ve modeli yukleyemedigini gosteriyor.
> 
> Colab'de dosya path'leri genelde `content/` ile baslar, senin yazdigin root dizin olan `/runs`in gercekten mevcut oldugundan emin misin? Dogrusu `runs` seklinde bir relative path olabilir mi?

Pip ile train ettiğimde ağırlık dosyaları orada oluyor. Modeli taşımak yerine direk yolu kopyala kısmından yol verdim. Colab üzerinde torch/yolov5/sahi versiyonları güncelledikten sonra cpu üzerinde denediğimde hata almadan çıktı alabildim.

**Comment by kadirnar** [comment]
> @kadirnar bilgiler icin cok tesekkurler.
> 
> Oncelikle sahi versiyonunu `pip install -U sahi` diyerek son surume guncelleyebilir misin? Bircok bugfix geldi [v0.8.9](https://github.com/obss/sahi/releases/tag/0.8.9) ile birlikte :)
> 
> Sonrasinda bu sekilde sliced olmayan standard prediction almayi deneyip nasil output verdigini bildirebilir misin?
> 
> ```python
> from sahi.model import Yolov5DetectionModel
> from sahi.predict import get_prediction
> 
> detection_model = Yolov5DetectionModel(
>    model_path="/runs/train/exp2/weights/best.pt'",
>    confidence_threshold=0.25,
>    device="cuda:0",
> )
> 
> result = get_prediction("images/2.jpg", detection_model)
> 
> result.export_visuals(export_dir="demo_data/")
> ```
confidence_threshold=0.25 resmin çıktısında 0 object tespiti var. En yüksek doğruluk değeri 0.12

Çıktısı :  [sahi.docx](https://github.com/obss/sahi/files/7566468/sahi.docx)

confidence_threshold=0.1 yaptığımda,

Çıktısı:  [sahi-2.docx](https://github.com/obss/sahi/files/7566471/sahi-2.docx)

Resim çıktısı: 
![prediction_visual](https://user-images.githubusercontent.com/36204372/142507805-c312c809-4054-4f49-8b09-6ae2faf6efb7.png)

Model: https://drive.google.com/file/d/1-1xGrb7G_-jdZ6JB9AdLCXypkVEOnCdw/view?usp=sharing

**Comment by fcakyon** [comment]
> Model: https://drive.google.com/file/d/1-1xGrb7G_-jdZ6JB9AdLCXypkVEOnCdw/view?usp=sharing

@kadirnar bu model ile `yolov5 detect --weights best.pt --source images/` calistirdigim zaman hicbir tespit yapamiyor.

![1](https://user-images.githubusercontent.com/34196005/142509569-6b39e99f-c125-4a3b-b39c-5d48c9e9a90d.jpg)

Senin repondaki [Yolov5s Modeli Kullanarak Veri Setimizi Eğitelim](https://github.com/kadirnar/yolov5-pytorch/blob/main/README.md#yolov5s-modeli-kullanarak-veri-setimizi-e%C4%9Fitelim) basliginda verilen su komutu kullandigimda elmalari iyi buluyor: `yolov5 detect --source images/`

![1](https://user-images.githubusercontent.com/34196005/142509541-b07d6e31-2e3a-41d5-a755-680527ba7966.jpg)

Bu iki komutun farki, ilk komutta senin kendi egittigin weighti kullanirken ikinci komutta `--weights best.pt` diye weight belirtmedigin icin COCO ile pretrain edilmis weightleri kullaniyor. COCO datasetinde `apple` classi da oldugu icin iyi tespit yapiyor.

Bu noktada senin yolov5 modelinin elma tespitini niye ogrenmedigini arastirabiliriz. 10 epoch yetersiz kalmis olabilir mi? Loss ve accuracy plotlarini inceledigin zaman converge olmus gibi mi duruyor yoksa 50-100 epoch egitim almak daha da iyilestirir mi?

**Comment by kadirnar** [comment]
Yolov5s gibi küçük bir modeli 10 epoch da eğitip bu kadar yüksek başarı almasına şaşırmıştım 😅 Güzel bir model ile tekrardan sahi algoritmasını deneyeceğim. Yardım ettiğiniz için çok teşekkür ederim @fcakyon hocam.

**Comment by fcakyon** [comment]
`yolov5` ve `sahi` paketleri uzerinde denemeler yaptigin icin asil ben tesekkur ederim @kadirnar 💯 

`sahi` ve `yolov5` uzerinde hazirlayacagin her turlu acik kaynak calismada/tutorialde yardima hazirim, linkedin veya mail uzerinden de yazabilirsin bana 👍 

Ilerleyen surecte dokumantasyon noktasinda gordugun eksiklerin olursa her turlu feedbacke de acigim, ekleriz hemen 😎
