### ISSUE TITLE
Add fp16 support to yolov5 loader

### ISSUE THREAD

**Issue by g0lemXIV** [obss/sahi#289]
Hello,
I think `model.half()` can be an improvement when the yolov5 model is loading with Cuda support.

**Comment by fcakyon** [comment]
@g0lemXIV thanks a lot for your interest in the `sahi` package!

You can currently convert the yolov5 model to fp16 as:

```python
from sahi.model import Yolov5DetectionModel

# load yolov5 model
detection_model = Yolov5DetectionModel(
    model_path='yolov5s6.pt',
    confidence_threshold=0.3,
    device="cuda:0",
)

# convert to fp16
detection_model.model.half()
```
