### ISSUE TITLE
sahi usage best practices + result report

### ISSUE THREAD

**Issue by Camilochiang** [obss/sahi#302]
Excellence code! Just two question
1. In #274 you mention that by default saih run inference in both: slides and full image. Then you also mention that one should insert the tiles (cropped images) in your initial dataset for training YOLOv5. For me this is a conflict / trade off as you may change the RPN anchors of the model (therefore making it worse) . Isn't better to either run saih only in tiles with a trained models in the respective pictures (More precise) and then a second model with the full resolution images (Less precise, faster)?
1. How do you @fcakyon recommend to report results? Is not so obvious as you are running inference several times in some pixels (up to 5 times: 4 for slices and 1 for the full image)

**Comment by fcakyon** [comment]
@Camilochiang thanks a lot for your interest in `sahi`! 

> 1. In [Detect small and large targets at the same time using `sahi`? #274](https://github.com/obss/sahi/issues/274) you mention that by default saih run inference in both: slides and full image. Then you also mention that one should insert the tiles (cropped images) in your initial dataset for training YOLOv5. For me this is a conflict / trade off as you may change the RPN anchors of the model (therefore making it worse) . Isn't better to either run saih only in tiles with a trained models in the respective pictures (More precise) and then a second model with the full resolution images (Less precise, faster)?

You are definitely right on that. 2 Separate models with different prediction behaviour would yield the best results. However, most of the users want to train single model for multi-scale object detection which is the reason of the default parameters. You can disable full or sliced inference so you can train and perform prediction with two separate models using `sahi` 👍

**Comment by Grenaf** [comment]
> Excellence code! Just two question
> 
> 1. In [Detect small and large targets at the same time using `sahi`? #274](https://github.com/obss/sahi/issues/274) you mention that by default saih run inference in both: slides and full image. Then you also mention that one should insert the tiles (cropped images) in your initial dataset for training YOLOv5. For me this is a conflict / trade off as you may change the RPN anchors of the model (therefore making it worse) . Isn't better to either run saih only in tiles with a trained models in the respective pictures (More precise) and then a second model with the full resolution images (Less precise, faster)?
> 2. How do you @fcakyon recommend to report results? Is not so obvious as you are running inference several times in some pixels (up to 5 times: 4 for slices and 1 for the full image)

So is it necessary to separate the small target from the big target in the same picture, and mark its position in the background image that excludes the other side. For example, take a single target out of the picture and place it in another background picture？

**Comment by fcakyon** [comment]
> > Excellence code! Just two question
> > 
> > 1. In [Detect small and large targets at the same time using `sahi`? #274](https://github.com/obss/sahi/issues/274) you mention that by default saih run inference in both: slides and full image. Then you also mention that one should insert the tiles (cropped images) in your initial dataset for training YOLOv5. For me this is a conflict / trade off as you may change the RPN anchors of the model (therefore making it worse) . Isn't better to either run saih only in tiles with a trained models in the respective pictures (More precise) and then a second model with the full resolution images (Less precise, faster)?
> > 2. How do you @fcakyon recommend to report results? Is not so obvious as you are running inference several times in some pixels (up to 5 times: 4 for slices and 1 for the full image)
> 
> So is it necessary to separate the small target from the big target in the same picture, and mark its position in the background image that excludes the other side. For example, take a single target out of the picture and place it in another background picture？

I did not get your question unfortunately, can you be more clear please?

**Comment by Grenaf** [comment]
> > > Excellence code! Just two question
> > > 
> > > 1. In [Detect small and large targets at the same time using `sahi`? #274](https://github.com/obss/sahi/issues/274) you mention that by default saih run inference in both: slides and full image. Then you also mention that one should insert the tiles (cropped images) in your initial dataset for training YOLOv5. For me this is a conflict / trade off as you may change the RPN anchors of the model (therefore making it worse) . Isn't better to either run saih only in tiles with a trained models in the respective pictures (More precise) and then a second model with the full resolution images (Less precise, faster)?
> > > 2. How do you @fcakyon recommend to report results? Is not so obvious as you are running inference several times in some pixels (up to 5 times: 4 for slices and 1 for the full image)
> > 
> > 
> > So is it necessary to separate the small target from the big target in the same picture, and mark its position in the background image that excludes the other side. For example, take a single target out of the picture and place it in another background picture？
> 
> I did not get your question unfortunately, can you be more clear please?

![image](https://user-images.githubusercontent.com/73221711/145705529-56719429-8825-4119-b36a-b4649fb50776.png)
* For example like this，The resolution of the original picture is 10000x10000, put the big target and the small target in different 10000x10000 images, the small target image is trained by slice, and the big target image is trained by the original method.The final data set contains sliced pictures of small targets and original pictures of large targets, and then send them directly to the network for training.
* Finally, use slice prediction and normal prediction at the same time。I'm not sure if this is feasible, maybe it will be more troublesome.

**Comment by fcakyon** [comment]
@Grenaf thanks a lot for the detailed visuals!

First of all, you should not delete annotation from images. As far I understood you are mentioning about deleting the annotation from images based on the annotation area (but the object is still present in the image). So in all cases, all of the annotations should be present in all of of the images.

If there are multiscale objects in your dataset, you can go with 2 approaches:
1. Perform training with sliced+full images, perform `sahi` inference with default settings (standard+sliced inference)
2. Train 2 separate models: first with full images and second with sliced images, then perform `sahi` inference with `no_sliced_prediction=True` for the first model and `no_standard_prediction=True` for the second model, then combine predictions of two models.

**Comment by Grenaf** [comment]
* Maybe my expression is not clear,My mother tongue is not English, maybe there are some errors in my expression, I am sorry about that.
* If we use method one to train the network, the RPN anchor may change. Take the following figure as an example. I think this result is mainly caused by small targets. In the first method, both the sliced image and the original image in the data set contain small targets, and the large target is chopped up. The sliced image cannot contain its complete information. Take the yolov5 input terminal 640x640 as an example. If the slice image size is 640x640, the small target pixel is 10x10, and the small target pixel in the original image is also 10x10. However, after the yolov5 input terminal is resized, the slice image will not be resized, and the original image will be resized. The effective pixels of the target may become 1x1. Maybe this reason will cause the RPN anchor to change.I am a newcomer to machine learning, maybe my statement is not right?
![image](https://user-images.githubusercontent.com/73221711/145743763-875e7a09-405e-4712-88d6-cabfb997f225.png)

* In order to solve this problem, we can recreate two pictures, one picture only contains the big target (relabeling + original image training), and one picture only contains the small target (relabeling + slice image training). Now our data set is slice image + slice image (only small target) tag and original image + original image tag (only big target). In this way, small targets will not interfere with the RPN anchor. Maybe this method will be more troublesome. Instead of simply deleting the label from the original image, I created two new images and relabeled them.
![image](https://user-images.githubusercontent.com/73221711/145744195-56e9b84c-0307-45eb-8b07-3ceaca72129c.png)
* The way to create a new picture is similar to this
![image](https://user-images.githubusercontent.com/73221711/145745259-a00d4d88-4555-481e-9e37-06d901eca2c4.png)

**Comment by Camilochiang** [comment]
@Grenaf  Dude, What is your mother language? . I assume that you are in the east part of the world for your writing times, but still..

**Comment by fcakyon** [comment]
@Grenaf I understand your concerns but not sure if this image cropping approach would work.

Instead, you can train anchorless models (such as [varifocalnet](https://github.com/open-mmlab/mmdetection/tree/master/configs/vfnet), [autoassign](https://github.com/open-mmlab/mmdetection/tree/master/configs/autoassign), [reppoints](https://github.com/open-mmlab/mmdetection/tree/master/configs/reppoints), [sparse-rcnn](https://github.com/open-mmlab/mmdetection/tree/master/configs/sparse_rcnn), [fcos](https://github.com/open-mmlab/mmdetection/tree/master/configs/fcos), [centernet](https://github.com/open-mmlab/mmdetection/tree/master/configs/centernet)) to overcome this anchor mismatch issue.

**Comment by Grenaf** [comment]
* ha ha, I will try, if the follow-up result is valid, I will leave a message again，Thanks！

**Comment by isspid** [comment]
> @Grenaf thanks a lot for the detailed visuals!
> 
> First of all, you should not delete annotation from images. As far I understood you are mentioning about deleting the annotation from images based on the annotation area (but the object is still present in the image). So in all cases, all of the annotations should be present in all of of the images.
> 
> If there are multiscale objects in your dataset, you can go with 2 approaches:
> 
>     1. Perform training with sliced+full images, perform `sahi` inference with default settings (standard+sliced inference)
> 
>     2. Train 2 separate models: first with full images and second with sliced images, then perform `sahi` inference with `no_sliced_prediction=True` for the first model and `no_standard_prediction=True` for the second model, then combine predictions of two models.

@fcakyon I am interested in the approach mentioned in point no. 2. Is there an established way how to do that? If not what would be the best approach to go about it, in your opinion?

**Comment by fcakyon** [comment]
> > @Grenaf thanks a lot for the detailed visuals!
> > First of all, you should not delete annotation from images. As far I understood you are mentioning about deleting the annotation from images based on the annotation area (but the object is still present in the image). So in all cases, all of the annotations should be present in all of of the images.
> > If there are multiscale objects in your dataset, you can go with 2 approaches:
> > ```
> > 1. Perform training with sliced+full images, perform `sahi` inference with default settings (standard+sliced inference)
> > 
> > 2. Train 2 separate models: first with full images and second with sliced images, then perform `sahi` inference with `no_sliced_prediction=True` for the first model and `no_standard_prediction=True` for the second model, then combine predictions of two models.
> > ```
> 
> @fcakyon I am interested in the approach mentioned in point no. 2. Is there an established way how to do that? If not what would be the best approach to go about it, in your opinion?

@isspid 2nd approach is not implemented in sahi but you can easily manage that by:

-  train `model1` on sliced images, train `model2` on full images

-  init `detection_model_1` and `detection_model_2` using sahi model classes (`Yolov5DetectionModel`, `Detectron2DetectionModel` or `MmdetDetectionModel`) with trained `model1` and `model2` weight paths

- perform sliced inference using `detection_model_1` instance and [get_sliced_prediction](https://github.com/obss/sahi/blob/2cd75f051a33172320dbeda7ea6f2b10131c0a6c/sahi/predict.py#L113) function using `perform_standard_pred=False`:
```python
prediction_result_1 = get_sliced_prediction(
    image,
    detection_model=detection_model_1,
    slice_height=512,
    slice_width=512,
    perform_standard_pred=False
)
```

- perform standard inference using `detection_model_2` instance and [get_prediction](https://github.com/obss/sahi/blob/2cd75f051a33172320dbeda7ea6f2b10131c0a6c/sahi/predict.py#L39) function 
```python
prediction_result_2 = get_prediction(
    image,
    detection_model=detection_model_2,
)
```

- combine both predictions:
```python
prediction_result_1.object_prediction_list.extend(prediction_result_2.object_prediction_list)
```

- convert prediction result into coco result format:
```python
prediction_result_1.to_coco_predictions()
```

- export prediction visuals:
```python
prediction_result_1.export_visuals(export_dir)
```

**Comment by isspid** [comment]
When I visit Turkey, I have to buy you a coffee. Teşekkürler!

**Comment by fcakyon** [comment]
> When I visit Turkey, I have to buy you a coffee. Teşekkürler!

Haha you're welcome 😄 I would appreciate a flat-white ☕
