### ISSUE TITLE
slicing a coco dataset with negative images

### ISSUE THREAD

**Issue by monykini** [obss/sahi#304]
I'm new to the data science scene , But I think there should be some empty annotations to decrease the number of false positives ?
On that note , I found a small problem . 
With empty annotations while slicing I kept running into errors , and the reason was empty annotations 
slicing.py Line 84 , Function annotation_inside_slice doesnt check within itself if the annotations are empty , or it isn't checked for beforehand  , Please let me know if I'm doing something wrong ..... Thank you @fcakyon 
On a side note : You guys are amazing 

`slice_coco(
                coco_annotation_file_path=jsonsxD[i],
                image_dir=dirxD,
                output_coco_annotation_file_name="labels.json",
                ignore_negative_samples=False,
                output_dir=outdirsxD[i],
                slice_height=360,
                slice_width=640,
                overlap_height_ratio=0.2,
                overlap_width_ratio=0.2,
                min_area_ratio=0.1,
                verbose=False
            )`

I came up with a quick fix for now , which is just adding a try catch
![image](https://user-images.githubusercontent.com/62514659/145690691-f43268a4-347a-4590-8072-bc8bea9e8f34.png)
![image](https://user-images.githubusercontent.com/62514659/145690674-e09f1edc-d8c7-44bd-84b5-a1b58118bd02.png)

**Comment by fcakyon** [comment]
@monykini thanks a lot for your interest in `sahi`!

You are right, it is a best practice to contain negative images that does not contain any annotations!

In this line there is a check if image contains any annotations so `sahi` can handle negative images: https://github.com/obss/sahi/blob/e18ca0009698947e945aaee5b630dd62750a678d/sahi/slicing.py#L318

I assume your coco json contain annotations that does not have `bbox` field. For negative images there shouldn't exist any annotation object at all.

**Comment by monykini** [comment]
Aha ! That must be it ! The thing is I exported my currently working YOLOv5 dataset to COCOdataset using Fiftyone , which threw it off  somehow . Thank you for clarifying I'll go through the generated annotations in the json once again
