### ISSUE TITLE
Explanation of results values

### ISSUE THREAD

**Issue by tureckova** [obss/sahi#305]
Hello, I used the sahi coco analyze and evaluate scripts for results analysis (of course, using the same model and results.json file).
Should not the **bbox_mAP50** from the _sahi coco evaluate_ script and the value **C50** in Derek-P-R-curve from the _sahi coco analyze_ script be the same values? Viz picture below?

Thank you for your valuable advice.

![sahi_analyze](https://user-images.githubusercontent.com/32820891/145731904-20021812-a604-4906-8eac-0decc6d08a52.png)

**Comment by fcakyon** [comment]
@tureckova thanks a lot for this report! There may be differences in default values (area thresholds, number of maximum detection etc). Will look into it today 👍

**Comment by fcakyon** [comment]
@tureckova thanks a lot for your amazing contributions to `sahi`! :rocket: :tada:

as i mentioned earlier, default params were not matching between `sahi coco evaluate` and `sahi coco analyse`. This PR fixes it: https://github.com/obss/sahi/pull/306

**Comment by fcakyon** [comment]
![Screenshot from 2021-12-13 23-02-43](https://user-images.githubusercontent.com/34196005/145880784-1a56d12c-9855-45cf-abb7-49d78edc0714.png)

**Comment by fcakyon** [comment]
@tureckova you are right they should be increasing, let me see if i forgot to update

**Comment by fcakyon** [comment]
@tureckova you are right they should be increasing, just pushed a hotfix to @main branch, can you install from @main and check again if its fixed?

**Comment by tureckova** [comment]
@fcakyon now it looks good :+1:. Thank you!
![evaluate](https://user-images.githubusercontent.com/32820891/146153227-82fea84b-5faa-4189-b0df-b8ac05548ee6.png)
