### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by alijundi** [obss/sahi#312]
I am planning to pass full HD images or even bigger such as 4K. My question if put slicing parameter to 640 and there is an object in-between slices will that be detected? Meaning almost half in one slice and the other half is in the next slice.

What is the solution to this problem if it exists?

Thank you

**Comment by fcakyon** [comment]
@alijundi thanks for your question!

By default, `sahi` applies %20 overlap between slices, you can change it by `overlap_ratio_height` and `overlap_ratio_width`.

**Comment by alijundi** [comment]
@fcakyon thank you for your prompt answer. can you explain why in the colab notebook when I do:
!pip install -U torch sahi yolov5

i get:

 Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed boto3-1.20.25 botocore-1.23.25 fire-0.4.0 jmespath-0.10.0 opencv-python-4.5.4.60 pillow-8.4.0 pyyaml-6.0 s3transfer-0.5.0 sahi-0.8.15 terminaltables-3.1.10 thop-0.0.31.post2005241907 urllib3-1.25.11 yolov5-6.0.6
WARNING: The following packages were previously imported in this runtime:
  [PIL]
You must restart the runtime in order to use newly installed versions.

You can try it your self and see!

**Comment by alijundi** [comment]
I am sorry to bother again. I managed to download the library to windows and I am trying to run it on CPU not CUDA.

I get the following error when I do the detection:

```
12/21/2021 10:48:48 - INFO - yolov5.utils.torch_utils -   Model Summary: 283 layers, 7071633 parameters, 7071633 gradients, 16.4 GFLOPs
12/21/2021 10:48:48 - INFO - yolov5.models.yolo -
12/21/2021 10:48:48 - INFO - yolov5.models.yolo -   Adding AutoShape...
C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
```

After than it quits with no output or exported visuals. Any idea why is that?

**Comment by fcakyon** [comment]
It is not an error. It is a warning that does not prevent sahi. Everything works as expected. It is related with a bug introduced in torch 1.10 that prints incorrect warning message: https://github.com/pytorch/pytorch/issues/67598

> I am sorry to bother again. I managed to download the library to windows and I am trying to run it on CPU not CUDA.
> 
> I get the following error when I do the detection:
> 
> ```
> 12/21/2021 10:48:48 - INFO - yolov5.utils.torch_utils -   Model Summary: 283 layers, 7071633 parameters, 7071633 gradients, 16.4 GFLOPs
> 12/21/2021 10:48:48 - INFO - yolov5.models.yolo -
> 12/21/2021 10:48:48 - INFO - yolov5.models.yolo -   Adding AutoShape...
> C:\Users\administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
>   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
> ```
> 
> After than it quits with no output or exported visuals. Any idea why is that?

@alijundi Iit is not an error. It is a warning that does not prevent sahi. Everything works as expected. It is related with a bug introduced in torch 1.10 that prints incorrect warning message: https://github.com/pytorch/pytorch/issues/67598

**Comment by fcakyon** [comment]
> @fcakyon thank you for your prompt answer. can you explain why in the colab notebook when I do: !pip install -U torch sahi yolov5
> 
> i get:
> 
> Attempting uninstall: opencv-python Found existing installation: opencv-python 4.1.2.30 Uninstalling opencv-python-4.1.2.30: Successfully uninstalled opencv-python-4.1.2.30 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible. albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible. Successfully installed boto3-1.20.25 botocore-1.23.25 fire-0.4.0 jmespath-0.10.0 opencv-python-4.5.4.60 pillow-8.4.0 pyyaml-6.0 s3transfer-0.5.0 sahi-0.8.15 terminaltables-3.1.10 thop-0.0.31.post2005241907 urllib3-1.25.11 yolov5-6.0.6 WARNING: The following packages were previously imported in this runtime: [PIL] You must restart the runtime in order to use newly installed versions.
> 
> You can try it your self and see!

I have just tried it in Colab and the Colab notebooks works as intended without any issues. The dependency conflict error is related with preisntalled Colab packages and does not affect `sahi`. You can safely ignore them. Notebook restart is required for Pillow pacakge and after restarting the notebook everything works as expected.

**Comment by fcakyon** [comment]
@alijundi new version `0.9.0` is live, update your `sahi` with `pip install -U sahi` 🚀 

https://github.com/obss/sahi/releases/tag/0.9.0
