### ISSUE TITLE
The paths of the python files in the test folder are incorrect.

### ISSUE THREAD

**Issue by kadirnar** [obss/sahi#325]
Merhaba @fcakyon Hocam,

Test klasöründeki python dosyaların img_path değişkeni içindeki dosya yolları yanlış. Örnek:

https://github.com/obss/sahi/blob/main/tests/test_yolov5model.py#L45
``` 
image_path = "tests/data/small-vehicles1.jpeg"
```
Zaten bu işlem tests klasöründe yapılmaktadır. Bu yüzden doğru yol şu şekilde olmalıdır.
``` 
image_path = "data/small-vehicles1.jpeg"
```

Benim farkettiğim toplam 3 tane dosya var.
- https://github.com/obss/sahi/blob/main/tests/test_yolov5model.py
- https://github.com/obss/sahi/blob/main/tests/test_mmdetectionmodel.py
- https://github.com/obss/sahi/blob/main/tests/test_predict.py

**Comment by fcakyon** [comment]
Testler ana proje dizininden calistirilmali, o yuzden sorun yok su anki pathlerde :)
