### ISSUE TITLE
ModuleNotFoundError: No module named 'sahi.postprocess.legacy'

### ISSUE THREAD

**Issue by isspid** [obss/sahi#332]
Hello, thank you for taking your time to work on this repo, the idea is amazing. I tried to use it just now, but I am getting the error below, both on Google Colab (the one provided by you) and on my Windows laptop. Any ideas how to deal with it?

```Traceback (most recent call last):
  File "c:\Users\istaka\practice\prova.py", line 10, in <module>
    from sahi.predict import get_prediction, get_sliced_prediction, predict
  File "C:\Users\istaka\Anaconda3\envs\yolov5\lib\site-packages\sahi\predict.py", line 20, in <module>
    from sahi.postprocess.legacy.combine import UnionMergePostprocess
ModuleNotFoundError: No module named 'sahi.postprocess.legacy' ```

**Comment by fcakyon** [comment]
@isspid thanks a lot for your interest in `sahi`!

Can you try again with `v0.8.18`? You can update your `sahi` version by `pip install -U sahi`.

**Comment by isspid** [comment]
Now it is working, thanks a lot for the fast response, really appreciate it. Good luck!
