### ISSUE TITLE
using custom yolov5 model with `sahi`

### ISSUE THREAD

**Issue by isspid** [obss/sahi#334]
I am trying to follow the official Google Colab about sliced inference using Yolov5. I want to use it to apply sliced inference using a model I have trained on my own dataset. The dataset is of course different from the COCO dataset and also the classes are different. 

Is there a way we can run inference based on our custom classes?

**Comment by fcakyon** [comment]
@isspid thanks for your interest i `sahi`!

You can give your custom trained model path when initializing Yolov5DetectionModel:

```python
custom_model_path = 'path/to/your/model.pt'

detection_model = Yolov5DetectionModel(
    model_path=custom_model_path,
    confidence_threshold=0.3,
    device="cpu", # or 'cuda:0'
)
```

Category names are automatically extracted from your provided model 👍

**Comment by isspid** [comment]
Hey, thanks for the brief response, appreciate it as always.

That is why I tried but I got a detection named "bench" which is not part of my classes. I only have one class called "window".

I also tried to run sliced inference on my laptop, everything seems to work fine, I get information about the number of slices for each file, but inside the runs/exp folder I don't see anything, basically the folder is empty.

**Comment by fcakyon** [comment]
@isspid what is your model name, if its one of the original model names (as `yolov5s.pt`/`yolov5s6.pt`/`yolov5m.pt` etc.) you have to change it to something else.

Can you send me your sample code you are running to export visuals? Currently I cannot recreate ay of your mentioned issues.

**Comment by isspid** [comment]
![image](https://user-images.githubusercontent.com/91065022/148356330-8c45f743-cc84-4ed3-a3a3-d153d24e98ab.png)
Above you can see the code for declaring the model path.

![image](https://user-images.githubusercontent.com/91065022/148356475-a23723f8-de7a-47eb-bea6-074bdcfad56b.png)
Above the code for loading the model.

![image](https://user-images.githubusercontent.com/91065022/148356555-d4dac53d-61fe-4587-ae61-3e8caa148d7d.png)
Code for running inference.

![image](https://user-images.githubusercontent.com/91065022/148356635-4403858d-45d5-432c-9296-0e4962ce52fd.png)
Code for exporting visuals.


![image](https://user-images.githubusercontent.com/91065022/148356684-d57f9203-aacf-4a29-8b5e-5f20bfd30e98.png)
This is the result I get.

**Comment by isspid** [comment]
After trying again, it is working fine on Google Colab, but I am still getting empty folders on my laptop. Do you have a suggestion on what I can try for a fix?

**Comment by fcakyon** [comment]
@isspid it seems like something is wrong with your `best.pt`. Is it possible that you can send it so that i can inspects the fields of the model file?

**Comment by fcakyon** [comment]
> After trying again, it is working fine on Google Colab, but I am still getting empty folders on my laptop. Do you have a suggestion on what I can try for a fix?

What do you mean by getting empty folders? Are you using CLI or Python script, what is the command/script you are using?

On CLI are you sure that you are adding `--export_visual`?

**Comment by isspid** [comment]
This is the CLI input and output.
![image](https://user-images.githubusercontent.com/91065022/148358700-0091d5e0-21c3-44a7-8119-b78ed7a88310.png)

And this is the folder.
![image](https://user-images.githubusercontent.com/91065022/148358850-3c5cbd3e-8099-4a75-b6b1-6866e9799ef2.png)

**Comment by fcakyon** [comment]
@isspid what is your `sahi` and `yolov5`? Are you sure you are using the latest versions?

**Comment by isspid** [comment]
https://drive.google.com/file/d/196FDf2f6YWan23Q1kkG7c-McLFMd55IP/view?usp=sharing this is the best.pt model file that I am using.

I checked the versions of both yolov5 and sahi and they are up to date.

**Comment by fcakyon** [comment]
@isspid this is what i am getting as output:
![image](https://user-images.githubusercontent.com/34196005/148360774-2f54a859-3597-4803-9fb8-333703df591f.png)

**Comment by isspid** [comment]
is this after running it in the CLI? I got the same output from Google Colab, but when I run the CLI on my laptop, the process finishes without any errors but I don't get any predicted images on the /runs/exp folder, [as per this reply](https://github.com/obss/sahi/issues/334#issuecomment-1006399773).

**Comment by fcakyon** [comment]
I am running on CLI with your given commands on Windows10, python 3.9.7, cudatoolkit 11.3, pytorch 1.10.0, sahi 0.8.18.

**Comment by fcakyon** [comment]
Most probably you are having read/write right issues on those folders. Can you try on other disk (instead of C:) or other user?

**Comment by fcakyon** [comment]
@isspid i spotted the issue, it happens when you give single image path as `--source` and that path is not not under current working directory. Will try to understand the bug better 👍

**Comment by isspid** [comment]
thanks a lot for the help, I really appreciate it. Just take note that it also happens when the source is a directory and not a single image, probably in the same conditions that the source dir is not under the current working dir.

**Comment by fcakyon** [comment]
@isspid you are right, just pushed some updates fixing these cases on windows to the branch `fix-export`. Can you please `pip uninstall sahi` then `pip install git+https://github.com/obss/sahi.git@fix-export` and try again if its fixed?

**Comment by isspid** [comment]
@fcakyon Working flawlessly. Well done and thank you!

**Comment by fcakyon** [comment]
@isspid new version `0.9.0` is live, update your `sahi` with `pip install -U sahi` 🚀 

https://github.com/obss/sahi/releases/tag/0.9.0
