### ISSUE TITLE
How to insert SAHI into yolov5 source code 

### ISSUE THREAD

**Issue by XiangqingZhang** [obss/sahi#363]
I modified part of the yolov5 source code and don't want to use pip install yolov5， how can I insert SAHI ?

**Comment by fcakyon** [comment]
Hello @XiangqingZhang where do you want to insert SAHI into?
Which yolov5 source code have you modified?
Why dont you want to use pip install yolov5?

**Comment by XiangqingZhang** [comment]
Thanks for your reply. I changed yolov5-6.0 with tracking, counting for persons in aerial images. I want to replace yolov5 with SAHI in the inference output. So what can I do it

**Comment by fcakyon** [comment]
Unfortunately we dont support custom code implementations. You can take current yolov5/mmdet/detectron2 implementations as reference: https://github.com/obss/sahi/blob/main/sahi/model.py
