### ISSUE TITLE
YOLOV5 issue

### ISSUE THREAD

**Issue by zhuofalin** [obss/sahi#392]
The error is: **AttributeError: 'NoneType' object has no attribute 'names'**  when i run inference_for_yolov5.py
And the error is opening: [**sahi/model.py line 421**] 
@property
    def category_names(self):
        return self.model.names

**Comment by fcakyon** [comment]
Hello @zhuofalin!

This error is mostly caused by providing incorrect model path. If you could send me your model I can confirm it.

**Comment by zhuofalin** [comment]
i just run this demo from the url&nbsp;https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb, so ~~~
But i just run this inference_for_mmdetection.py demo from the&nbsp;&nbsp;&nbsp;https://colab.research.google.com .
so i want to solve those error by myself.&nbsp;
thank you! if i cannot,i will ask again~~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obss/sahi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 晚上8:09
***@***.***&gt;;
抄送:&nbsp;"剑客夜下思伊 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [obss/sahi] YOLOV5 issue (Issue #392)





 
Hello @zhuofalin!
 
This error is mostly caused by providing incorrect model path. If you could send me your model I can confirm it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fcakyon** [comment]
Hello @zhuofalin have you solved your issue? If not, can you give some more detail on your issue?

**Comment by zhuofalin** [comment]
Done!! 😀
Thank you for your help~ 谢谢👏
👍

**Comment by diable0709** [comment]
the error happen when I use device="cuda",
