### ISSUE TITLE
sahi on apple silicon mac

### ISSUE THREAD

**Issue by mustafaozx** [obss/sahi#393]
Hello everyone, I am encountering a mistake when installing SAHI. I think this error is due to the need for the fiftyone library. While installing Fiftyone, I left the error I received below.
<img width="944" alt="Screen Shot 2022-02-16 at 18 41 32" src="https://user-images.githubusercontent.com/59654574/154300638-679aa53f-cc39-4e50-a947-7dfe05cfb101.png">

I think it says a mongodb connection is required. But I wasn't sure if such a thing was necessary. ?
I'm waiting for your help.
Thank you.

**Comment by fcakyon** [comment]
Hello @mustafaozx, thanks a lot for bringing attention to this issue!

`fiftyone` is not a core dependency and required only for interactive visualization. You can use the other `sahi` features without installing `fiftyone` 👍
