### ISSUE TITLE
inference with videos and the speed fps of sahi

### ISSUE THREAD

**Issue by XiangqingZhang** [obss/sahi#401]

**Comment by XiangqingZhang** [comment]
Hi， can I detect with yolov5 by inputting video?

**Comment by fcakyon** [comment]
@XiangqingZhang currently SAHI doesnt support video input. It supports single image and a folder of image as input. FPS depends on the detector used.

**Comment by fcakyon** [comment]
@zxq309 sahi v0.9.3 brings video inference support for all Detectron2/MMDetection/YOLOv5 models! Check https://github.com/obss/sahi/releases/tag/0.9.3
