### ISSUE TITLE
how to use my own yolov5 model to infer

### ISSUE THREAD

**Issue by 66Ethanwang** [obss/sahi#409]
Excuse me，i trained my own yolov5 model and i already added opts in to the commen.py ,but It can't read the correct parameters of the backbone，I don't know if I overlooked something。

Below is my backbone parameter：
yolov5.models.yolo -     0                -1  1      3520  yolov5.models.common.Conv               [3, 32, 6, 2, 2]              
 yolov5.models.yolo -    1                -1  1      1932  yolov5.models.common.RepVGGBlock        [128, 3, 2]                   
yolov5.models.yolo -     2                -1  1     16768  yolov5.models.common.C3                 [32, 64, 1]                   
yolov5.models.yolo -     3                -1  1      3852  yolov5.models.common.RepVGGBlock        [256, 3, 2]

**Comment by kadirnar** [comment]
To test the custom Yolov5 model you should follow the steps here.

https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb
or 
https://github.com/kadirnar/yolov5-pytorch-sahi/blob/main/yolov5_sahi.py

**Comment by 66Ethanwang** [comment]
got it ,and thanks  a lot.
I finally found the reason for this problem because I modified the operator in the file common.py

**Comment by fcakyon** [comment]
@66Ethanwang yes custom implementations of yolov5 are not supported on the fly, you have to update sahi/models.py for your needs 👍

**Comment by 66Ethanwang** [comment]
got it,but i have another question , in the function get_sliced_prediction ,i set the  slice_height=1680,and slice_width=1680, After image slicing，Yolov5 does it directly use (1680，1680) to predict? Or where it will use the letter_box? i debug many times but I couldn't find the answer.

**Comment by fcakyon** [comment]
@66Ethanwang by default yolov5 will perform inference on 640 size, you can update `image_size` param at Yolov5DetectionModel class init.
