### ISSUE TITLE
Fine-Tuning Details about your proposal

### ISSUE THREAD

**Issue by IvanGarcia7** [obss/sahi#416]
Good morning.

I have been reading your proposal and would like to cite it in one of my papers. However, I would like to clarify some details. I have seen that it is contemplated the re-training applying SAHI.

How does it work exactly, do you re-train with the outputs obtained after applying YOLOv5+SAHI or do you use the dataset dedicated to Visdrone training already annotated previously?

On the other hand, I would like to get the json files to generate the mAPs set in the experimental phase according to your ablation study.

**Comment by fcakyon** [comment]
Hello @IvanGarcia7, thanks for your interest in SAHI!

Let's continue the paper related discussion here: https://github.com/fcakyon/sahi-benchmark/issues/1
