### ISSUE TITLE
Can I obtain a simil file like the file from the command --save-txt of Yolov5?

### ISSUE THREAD

**Issue by claudio9russo7** [obss/sahi#420]
Hello
i didn't find anything but maybe i'm looking wrong, is it possible to get a txt file like the one you get by doing the inference with yolov5 on the pictures?

**Comment by fcakyon** [comment]
@claudio9russo7 you can export coco result json file by providing dataset json to the predict command: https://github.com/obss/sahi/issues/356

**Comment by claudio9russo7** [comment]
Yep, solve my issue, I just want to suggest adding a possible choice of export format like .json or .txt :D

**Comment by fcakyon** [comment]
@claudio9russo7 noted it, will look into that feature when I find some time 🚀
