### ISSUE TITLE
Empty  predictions in output directory

### ISSUE THREAD

**Issue by saidineshpola** [obss/sahi#421]
I tried using `sahi predict` command to generate predictions for mmdet model, but the output directory is empty. I also changed the threshold, but it didn't help. I am getting inference result on single image but it fails when I use the predict command.

**Comment by fcakyon** [comment]
@saidineshpola are you providing `--export_visual` arg to `sahi predict` command? By default it wont export the prediction visuals.

**Comment by saidineshpola** [comment]
No, I didn't include `--export_visual` arg. In fact, I'm looking for predictions in json format. It didn't even make make predictions in the output file, so I used your single-image inference to make predictions for a folder containing images.
