### ISSUE TITLE
Is the sahi input form array for yolov5 forward?

### ISSUE THREAD

**Issue by youngjae-avikus** [obss/sahi#426]
Hello
Can you tell me why it's not Torch but numpy?
Is it possible if it's np input?

**Comment by youngjae-avikus** [comment]
Ah because of `AutoShape` default True

What is the difference between AutoShape and basic yolov5 modules?

Thank you!

**Comment by fcakyon** [comment]
We wanted `sahi` to work independent from torch thats why all detectors accept numpy or str as image input 👍

**Comment by fcakyon** [comment]
> What is the difference between AutoShape and basic yolov5 modules?

You should ask the yolov5 related questions in ultralytics/yolov5 repo 🚀
