### ISSUE TITLE
The output is empty when batch processing

### ISSUE THREAD

**Issue by farawayeast** [obss/sahi#430]
hello
According to the provided tutorial, for a single image processing, the output is normal, when batch processing, the file can be detected, and the progress bar also shows the processing of the image, but the output folder /runs/predict/exp is empty. how can I solve this problem?

**Comment by fcakyon** [comment]
Hello @farawayeast, thanks a lot for pointing that out! You have to add `export_visual=True` for `predict` function as:

```python
predict(
    model_type=model_type,
    model_path=model_path,
    model_device=model_device,
    model_confidence_threshold=model_confidence_threshold,
    source=source_image_dir,
    slice_height=slice_height,
    slice_width=slice_width,
    overlap_height_ratio=overlap_height_ratio,
    overlap_width_ratio=overlap_width_ratio,
    export_visual=True
)
```

We will fix the notebooks in the following days :+1:

**Comment by fcakyon** [comment]
`export_visual=True` behavior is replaced with `novisual=False` behavior.

Default is `novisual=False` and will export visuals. To omit visual export add `--novisual` argument or set `novisual=False`.
