### ISSUE TITLE
Currently is it compatible with yolov5 6.1?

### ISSUE THREAD

**Issue by youngjae-avikus** [obss/sahi#438]
I used sahi with 6.1 temporarily because of the compatible trt model
Fortunately, the `yolov5-pip 6.1` version has become release
But is it compatible with Sahi right now? Thank you.

**Comment by youngjae-avikus** [comment]
In addition, it was a pity that there was no benchmark for FPS in the paper,
but is there any part that was organized separately?
I'm curious how much margin I can take
Thank you!

**Comment by fcakyon** [comment]
Hello @youngjae-aviku, `sahi` package is being automatically tested in daily basis with `yolov5 v6.1.0`: https://github.com/obss/sahi/blob/d58f61099d6f2f592379a7461f730ace21f7b572/.github/workflows/package_testing.yml#L72 we can assume it would be compatible.
