### ISSUE TITLE
Eval json problem, don't show any statistic.

### ISSUE THREAD

**Issue by claudio9russo7** [obss/sahi#446]
I ran the "predict" command providing the .json file associated with the photos:

!sahi predict  --source /content/drive/MyDrive/ColabNotebooks/WeedNew/Test --dataset_json_path /content/drive/MyDrive/ColabNotebooks/WeedNew/Test/test.json  --model_type yolov5 --model_path /content/drive/MyDrive/ColabNotebooks/WeedNew/weed6.pt --slice_height 640 --slice_width 640 --export_visual --overlap_height_ratio 0.4 --overlap_width_ratio 0.4  --export_pickle

Then i use the coco evaluate

!sahi coco evaluate --dataset_json_path /content/drive/MyDrive/ColabNotebooks/WeedNew/Test/test.json  --result_json_path /content/runs/predict/exp2/result.json 

But i get this: 

![eval](https://user-images.githubusercontent.com/99536010/163787501-ee9098a9-5771-4f85-a1b9-2f43daf6d876.png)

Viewing the visuals with ground truth I see errors, but the results in general are excellent, I don't understand why it gives me those numbers.

**Comment by claudio9russo7** [comment]
Here some images with GT
![Optimized-IMG_20220127_112624](https://user-images.githubusercontent.com/99536010/163792178-2a8ebecb-1754-425d-a231-2918d451f044.png)
![Optimized-IMG_20220127_112641](https://user-images.githubusercontent.com/99536010/163792272-3db2ca40-3ddb-424f-89ef-6cf060f9fc38.png)

**Comment by fcakyon** [comment]
@claudio9russo7 have you your dataset.json category ids are properly set, see this discussion on how to update your dataset categories: https://github.com/obss/sahi/issues/273#issuecomment-992317552

**Comment by claudio9russo7** [comment]
Thanks for the quick reply, I checked as you said. Actually the ids were wrong by 1. I fixed the problem, making them match, but unfortunately the problem persists.
![eval1](https://user-images.githubusercontent.com/99536010/163890269-0101e85a-544e-404a-9b44-7c17d89ea7a6.png)

Training the model I got a mAP of 0.3, and from the photos I see it does a good job. I don't understand these statistics

**Comment by claudio9russo7** [comment]
I solved the category_id problem, now I'm sure. As you said it was the only problem, in fact now I have consistent numbers.
Thanks @fcakyon.
![eval2](https://user-images.githubusercontent.com/99536010/163947215-9feedc6e-161b-49c5-9cc4-4cad099732ad.png)
