### ISSUE TITLE
There is no result in run/predict folder

### ISSUE THREAD

**Issue by hubery1619** [obss/sahi#454]
Hi, after the following command:
sahi predict --no_sliced_prediction --model_type yolov5 --source tests/data/coco_utils/terrain1.jpg --model_path tests/data/models/yolov5/yolov5s6.pt --image_size 320

I could not see the generated image in run/predict although it could run successfully without error.

**Comment by spatiallysaying** [comment]
I get a similar issue with CLI version.

`!sahi predict --source /content/Geotiff/ --model_type detectron2 --model_path /content/output/model_final.pth  --slice_height 512 --slice_width 512`

This info shows 100% inference.
```
04/30/2022 11:08:24 - WARNING - sahi.model -   tuple index out of range
Performing prediction on 32 number of slices.
Performing inference on images:   0% 0/1 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.7/dist-packages/sahi/postprocess/utils.py:145: RuntimeWarning: invalid value encountered in long_scalars
  return intersect / smaller_area
Performing inference on images: 100% 1/1 [00:03<00:00,  3.76s/it]
```

However,  '/content/runs/predict/exp' folder is empty

**Comment by fcakyon** [comment]
Hello @spatiallysaying you have to add `--export_visual` argument if you want to see the prediction visuals. Ccheck CLI docs for more detail: https://github.com/obss/sahi/blob/main/docs/cli.md#predict-command-usage
