### ISSUE TITLE
Sliced folder to image

### ISSUE THREAD

**Issue by spatiallysaying** [obss/sahi#456]
This is not an issue. A request to include a sample for constructing an image from sliced images folder.

The below snippet from you [article ](https://medium.com/codable/sahi-a-vision-library-for-performing-sliced-inference-on-large-images-small-objects-c8b086af3b80) slices a given image. Could you share a snippet for reverse process.
```
from sahi.slicing import slice_image
slice_image_result, num_total_invalid_segmentation = slice_image(
    image=image_path,
    output_file_name=output_file_name,
    output_dir=output_dir,
    slice_height=256,
    slice_width=256,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
)
```

**Comment by fcakyon** [comment]
Hello @spatiallysaying, what do you mean by the `reverse process`? Why do you need to combine sliced images (you already have the original one since you sliced it)
