### ISSUE TITLE
Are there different methods to add models?

### ISSUE THREAD

**Issue by kadirnar** [obss/sahi#476]
Merhabalar,

SAHI kütüphanesinin farklı algoritmalarla nasıl çalıştığını test etmek istiyorum. Model.py dosyasında işlem yapmadan gelen score,bbox,category_name, category_id değerlerini ObjectPrediction fonksiyonun içinde tanımlamak yeterli mi? 

[Dethub](https://github.com/kadirnar/dethub/blob/main/dethub/model.py#L56-L66) bu projede istenen değişkenleri bir sözlükte tutuyorum. En basit şekilde SAHI'ye nasıl entegre edebilirim?

**Comment by fcakyon** [comment]
Merhaba Kadir,

Farkli algoritmalardan kastettigin nedir, detaylandirabilir misin? Obje tespit modelleri mi?

Test etmek istedigin sey nedir bir de, biraz acabilir misin? Sliced inference sonuclari mi? Standard inference sonuclari mi? Evaluation sonuclari mi? Gorsellestirmeler mi?

**Comment by kadirnar** [comment]
SAHI'nin desteklemediği nesne tespit modelleri(Tfhub,NanoDet,scaled-yolov4...) ve takip algoritmalarını test etmek istiyorum.

[DeepSort][https://github.com/kadirnar/Yolo-Deepsort/blob/main/track.py#L194] burada deepsort çıktıları mevcut. Bunu SAHI'ye aktardığımızdaki Sliced inference sonucunu performansı ölçmek istiyorum. Daha stabil ve yüksek doğruluklu bir sonuç alıp alamayacağımı test etmek istiyorum.

**Comment by kadirnar** [comment]
Cevabınız için teşekkür ederim.
