### ISSUE TITLE
refactor demo notebooks by utilizing newly introduced AutoDetectionModel

### ISSUE THREAD

**Issue by fcakyon** [obss/sahi#497]
https://github.com/obss/sahi/blob/main/demo/inference_for_detectron2.ipynb
https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb
https://github.com/obss/sahi/blob/main/demo/inference_for_mmdetection.ipynb
https://github.com/obss/sahi/blob/main/demo/inference_for_huggingface.ipynb

Instead of: 
```python
from sahi.models import Yolov5DetectionModel

# load yolov5 models
detection_model = Yolov5DetectionModel(
    model_path='yolov5s.pt',
    image_size=640,
)
```
Replace with this:
```python
from sahi import AutoDetectionModel

# load yolov5 models
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov5',
    model_path='yolov5s.pt',
    image_size=640,
)
```

for all demo notebooks.

**Comment by ishworii** [comment]
I would like to help with this issue.

**Comment by fcakyon** [comment]
@ishworii awesome! after this PR you are free to open a PR :rocket: 

Now instead of `AutoDetectionModel.from_local(`, it will be `AutoDetectionModel.from_pretrained(` :+1:

**Comment by ishworii** [comment]
Only this notebook
https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb
has the mentioned import. So, I guess I will change only this?

**Comment by fcakyon** [comment]
@ishworii not only that, for instance detectron2 notebook has `Detectron2DetectionModel ` which should be replaced with 

```python
detection_model = AutoDetectionModel.from_pretrained(
    model_type='detectron2',
    model_path=model_path,
    confidence_threshold=0.5,
    image_size=640,
    device="cpu", # or 'cuda:0'
)

or huggingface notebook has `HuggingfaceDetectionModel` which should be replaced with 

```python
detection_model = AutoDetectionModel.from_pretrained(
    model_type='huggingface',
    model_path=model_path,
    confidence_threshold=0.5,
    image_size=640,
    device="cpu", # or 'cuda:0'
)
```

of torchvision notebook has `TorchVisionDetectionModel` which should be replaced with 

```python
detection_model = AutoDetectionModel.from_pretrained(
    model_type='torchvision',
    model=model,
    confidence_threshold=0.5,
    image_size=640,
    device="cpu", # or 'cuda:0'
)
```

**Comment by fcakyon** [comment]
`AutoDetectionModel` is the new, updated, prefered and easier way of loading models :) So it would be better to update the notebooks accordingly 👍
