### ISSUE TITLE
What does segment mask mean in ObjectPrediction class?

### ISSUE THREAD

**Issue by youngjae-avikus** [obss/sahi#519]
Mask merge is also done in the code below, 
is there a case where a mask is provided in the object detection task?
Is this used for multimodal tasks?

https://github.com/obss/sahi/blob/095b1e74e7bc1abe9ebbc10eeb5a2e0bd4a8ae0e/sahi/postprocess/utils.py#L193-L216

**Comment by youngjae-avikus** [comment]
In addition, wouldn't `merge_ind_list` need to be sorted in descending order once before the for statement action?

https://github.com/obss/sahi/blob/095b1e74e7bc1abe9ebbc10eeb5a2e0bd4a8ae0e/sahi/postprocess/combine.py#L518-L529

**Comment by fcakyon** [comment]
Hello @youngjae-avikus, SAHI framework currently supports the instance segmentation models in MMDetection. These mask merging operations are only used in instance segmentation models (not used in object detection models).
