### ISSUE TITLE
Question about integrating sahi in yolov5

### ISSUE THREAD

**Issue by lchunleo** [obss/sahi#520]
Hi
 Thanks for sharing the great work. However, i wish to know how can i integrate the sahi as part of the yolov5 inference? in the example e.g. for the yolov5, it seem that it is working outside of the yolov5. my wish is to have a real time video stream that comes in and then using the sahi to do the small object detection with yolov5.

And if the model is trained with the standard method (without sahi), does applying sahi to the incoming videos have any meaningful outcome? 

Please advise if my understanding is incorrect. thank you

**Comment by lchunleo** [comment]
thanks @fcakyon for replying. oh, i meant by that statement, "seem working outside of yolov5"   to using yolov5 as a cli instead of inside the code. i might be wrong, since you have pointed out, let me do a check on the model.py to get better understanding. Thank you for your reference.

**Comment by fcakyon** [comment]
sahi uses yolov5 inside the code. Check this notebook for using yolov5 with sahi: https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb

Here is the source code for yolov5 in sahi if you want it: https://github.com/obss/sahi/blob/91a0becb0d86f0943c57f966a86a845a70c0eb77/sahi/model.py#L372
