### ISSUE TITLE
sahi predict error

### ISSUE THREAD

**Issue by wgq18** [obss/sahi#522]
I use command
 'sahi predict --source small-vehicles1.jpeg --model_type yolov5 --model_path yolov5s.pt --export_visual --no_standard_prediction --slice_height 640 --slice_width 640 --model_confidence_threshold 0.4  --model_device cpu'
 to detect images but get error 
''anaconda3/envs/sahi_yolov5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: random_device could not be read"

My env is python3.7 pytorch1.10 cuda11.1, how to fix this problem?

**Comment by fcakyon** [comment]
@wgq18 have you tried prediction with gpu as `--model_device cuda:0'`

**Comment by wgq18** [comment]
When I use 
'sahi predict --source small-vehicles1.jpeg --model_type yolov5 --model_path yolov5s.pt --export_visual --no_standard_prediction --slice_height 640 --slice_width 640 --model_confidence_threshold 0.4  --model_device cuda:0'
My terminal halt and output nothing.
I use ctrl+C, then get 
'Traceback (most recent call last):
  File "/home/wangpo/anaconda3/envs/sahi_yolov5/bin/sahi", line 8, in <module>
    sys.exit(app())
'
'File "/home/wangpo/anaconda3/envs/sahi_yolov5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
KeyboardInterrupt
'
Please tell me which is wrong.

**Comment by wgq18** [comment]
I want to know what's your python, pytorch and cuda version? Thank you.

**Comment by fcakyon** [comment]
@wgq18 adviced installations steps are given in https://github.com/obss/sahi#installation

<summary>
<big><b>Installation details:</b></big>
</summary>

- Install `sahi` using pip:

```console
pip install sahi
```

- On Windows, `Shapely` needs to be installed via Conda:

```console
conda install -c conda-forge shapely
```

- Install your desired version of pytorch and torchvision:

```console
conda install pytorch=1.10.2 torchvision=0.11.3 cudatoolkit=11.3 -c pytorch
```
  
- Install your desired detection framework (yolov5):

```console
pip install yolov5==6.1.3
```

- Install your desired detection framework (mmdet):

```console
pip install mmcv-full==1.5.3 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
```

```console
pip install mmdet==2.25.0
```

- Install your desired detection framework (detectron2):

```console
pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
```

- Install your desired detection framework (huggingface):

```console
pip install transformers timm
```

</details>

**Comment by fcakyon** [comment]
> When I use 'sahi predict --source small-vehicles1.jpeg --model_type yolov5 --model_path yolov5s.pt --export_visual --no_standard_prediction --slice_height 640 --slice_width 640 --model_confidence_threshold 0.4 --model_device cuda:0' My terminal halt and output nothing. I use ctrl+C, then get 'Traceback (most recent call last): File "/home/wangpo/anaconda3/envs/sahi_yolov5/bin/sahi", line 8, in sys.exit(app()) ' 'File "/home/wangpo/anaconda3/envs/sahi_yolov5/lib/python3.7/site-packages/torch/cuda/**init**.py", line 214, in _lazy_init torch._C._cuda_init() KeyboardInterrupt ' Please tell me which is wrong.

What is your SAHI version?

**Comment by wgq18** [comment]
sahi version 0.10.1, yolov5 version 6.1.6.

**Comment by wgq18** [comment]
I only use yolov5. So mmdet, detectron2 and huggingface is not needed, right?

**Comment by fcakyon** [comment]
> I only use yolov5. So mmdet, detectron2 and huggingface is not needed, right?

You are right 👍

**Comment by wgq18** [comment]
Have you tested the lastest sahi on cuda11.1? My cuda is 11.1, but your guide is 11.3. So can you give me an example about running sahi on cuda11.1?

**Comment by fcakyon** [comment]
I currently dont have the time to test it in cuda11.1, maybe @devrimcavusoglu could try to recreate it if he has the time

**Comment by wgq18** [comment]
Thank you for your help, my problem is solved. Now I want to add sahi inference to my yolov7 detector, can you give me tutorial?

**Comment by fcakyon** [comment]
@wgq18 would you mind sharing how you solved your issue?

To add support to new detector, you follow the instructions here: https://github.com/obss/sahi#contributing
