### ISSUE TITLE
Can PCB be detected

### ISSUE THREAD

**Issue by monkeycc** [obss/sahi#523]
![1111](https://user-images.githubusercontent.com/6490927/179889638-a8ca2087-0ba0-4589-8d60-126ce94806b3.jpg)

9000*9000
Can PCB be detected

Need detection

Resistor chip
Whether it exists
Whether there are defects

**Comment by fcakyon** [comment]
Here is what you can do:
1. annotate defect/chip boxes in coco format
2. slice coco dataset
3. train yolov5/mmdetection detector on sliced dataset
4. perform sahi inference using your trained model and preferred slice size
