### ISSUE TITLE
sahi coco yolov5  Label class 3 exceeds nc=3 . Possible class labels are 0-2

### ISSUE THREAD

**Issue by monkeycc** [obss/sahi#524]
```
optimizer: SGD with parameter groups 59 weight (no decay), 62 weight, 62 bias
train: Scanning 'E:\yolov5\hello\train' images and labels...37 found, 0 missing, 30 empty, 0 corrupt: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:02<00:00, 14.10it/s]
train: New cache created: E:\yolov5\hello\train.cache
Traceback (most recent call last):
  File "train.py", line 643, in <module>
    main(opt)
  File "train.py", line 539, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 230, in train
    assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
AssertionError: Label class 3 exceeds nc=3 in E:\yolov5\data\hello.yaml. Possible class labels are 0-2
```

```
sahi coco yolov5 --image_dir D:\sahi\demo\demo_data\sliced --dataset_json_path D:\sahi\demo\demo_data\sliced\sliced_coco.json_coco.json  --train_split 0.9
```

**exp/data.yml**
```
names: [Tong_wu, Tong_Ban, CaHen]
nc: 3
train: D:\sahi\demo\demo_data\runs\coco2yolov5\exp\train
val: D:\sahi\demo\demo_data\runs\coco2yolov5\exp\val
```

nc: 3
Why prompt error

txt
Label class  ID
1-3

yolov5 Is it ID 0-3 ?
But I don't know how to adjust it
It is not clear whether this problem caused

**Comment by fcakyon** [comment]
Your annotations ids are incorrect. Yolo requires category ids as 0-2. It says in the error you posted.

**Comment by monkeycc** [comment]
LabelImg 
annotations ids
0-2

but
sahi coco yolov5 --image_dir D:\sahi\demo\demo_data\sliced --dataset_json_path D:\sahi\demo\demo_data\sliced\sliced_coco.json_coco.json  --train_split 0.9

Sahi conversion automatically increases by 1
id + 1

annotations ids
1-3

How to solve Sahi automatic adding 1

Convert to coco format
Coco format leads to?

**Comment by fcakyon** [comment]
> Sahi conversion automatically increases by 1 id + 1

This is not true.

Can you please upload `LabelImg` annotation file?

**Comment by monkeycc** [comment]
MyDataset/ 
|--PCB_COCO_images_640_02_VOC/  # LabelImg
|  |--1.jpg
|  |--1.txt
|  |--2.jpg
|  |--2.txt
|  |--...
|  |--...
|
|--runs/
|----coco2yolov5/   #    sahi coco yolov5 ....  slice_coco
|----slice_coco/      #  sahi coco slice  ...  PCB_COCO.json .....
|
|  |--labelimg2COCO.py    # PCB_COCO_images_640_02_VOC  labelimg2COCO 
|  |--PCB_COCO.json         # PCB_COCO_images_640_02_VOC  labelimg2COCO json


[PCB_COCO_images_640_02_VOC.zip](https://github.com/obss/sahi/files/9174146/PCB_COCO_images_640_02_VOC.zip)


I doubt abelimg2COCO.py  has a problem
ID ?

xview_ to_ coco.py
visdrone_ to_ coco.py
But I don't find any official examples like this

Thank you for your help
@fcakyon

**Comment by fcakyon** [comment]
labelimg2COCO.py adds 1 to category id which is incorrect:

```python
def addCatItem(name):
    global category_item_id
    category_item = dict()
    category_item['supercategory'] = 'none'
    category_item_id += 1
    category_item['id'] = category_item_id
    category_item['name'] = name
    coco['categories'].append(category_item)
    category_set[name] = category_item_id
    return category_item_id
```

**Comment by fcakyon** [comment]
labelimg2COCO.py starts category id from 1 which is incorrect:

```python
def addCatItem(name):
    global category_item_id
    category_item = dict()
    category_item['supercategory'] = 'none'
    category_item_id += 1
    category_item['id'] = category_item_id
    category_item['name'] = name
    coco['categories'].append(category_item)
    category_set[name] = category_item_id
    return category_item_id
```

Please write a proper voc to coco conversion script.
