### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by seekingdeep** [obss/sahi#526]
Peace be upon you

When running Sahi
```
(yolo) home@home-lnx:~/programs/yolov5$  sahi predict --source 1.jpg --model_type yolov5 --model_path ./best.pt --slice_height 256 --slice_width 256
Segmentation fault (core dumped)
```

steps to recreate:
```
conda create -n yolo python=3.9
conda activate yolo
pip install sahi
conda install pytorch=1.10.2 torchvision=0.11.3 cudatoolkit=11.3 -c pytorch
pip install yolov5
sahi predict --source 1.jpg --model_type yolov5 --model_path ./best.pt --slice_height 256 --slice_width 256
```

Note:
- python 3.9 i even tried python 3.7
- sahi 0.10.1
- pytorch=1.10.2 torchvision=0.11.3 cudatoolkit=11.3
- yolov5 6.1.6

**Comment by fcakyon** [comment]
Can you please paste here the full error trace?

**Comment by wgq18** [comment]
I met the same problem and find error about 'import torch'. I added 'import torch' in the first line of yolov5_sahi.py and solved this problem. But I don't know how to solve this problem when use 'sahi predict' command. @fcakyon

**Comment by wgq18** [comment]
I want to add sahi inference to Megvii yolox detector or yolov7 detector, can you give me some guide or demo? Please email 1017892298@qq.com, thank you. @seekingdeep

**Comment by kadirnar** [comment]
> I want to add sahi inference to Megvii yolox detector or yolov7 detector, can you give me some guide or demo? Please email [1017892298@qq.com](mailto:1017892298@qq.com), thank you. @seekingdeep

Hi @wgq18 ,

You can run the YOLOX model using the MMDetection library.
YOLOX+ SAHI: https://huggingface.co/spaces/fcakyon/sahi-yolox 

To add the Yolov7 library, simply write the inference code.  I combined the Yolov6 model with SAHI.
https://github.com/kadirnar/Yolov6-SAHI/blob/main/sahi/model.py#L1087-L1135

A pip version will be released for yolov7 soon. After the pip version is out, I will add it to the SAHI library.
Yolov7-Pip:
https://github.com/open-yolo/yolov7/tree/main
