### ISSUE TITLE
Add code formatting as a script

### ISSUE THREAD

**Issue by devrimcavusoglu** [obss/sahi#537]
Code formatting need to be individually handled for black and isort, this can be combined into a single script.

**Comment by kadirnar** [comment]
Hi @devrimcavusoglu ,

Why do we do this manually?

Example:
https://github.com/gradsflow/gradsflow/blob/main/.pre-commit-config.yaml

Why don't we add the  pre-commit-config.yaml file for SAHI? @fcakyon

**Comment by devrimcavusoglu** [comment]
Hi @kadirnar, the main reason is that some tools is not used for formatting and only for check (e.g. `flake8`). Since we can only perform check and not formatting on flake8, some changes may be required to be done manually.

Another reason is that, code formatting tools does not take strings / docstrings into account while formatting afaik, so those also have to be done manually. That's why we prefer only checking the code style in CI and not formatting automatically.

**Comment by fcakyon** [comment]
Also, I had a lot of issues and errors on Windows while setting up and using pre-commit :imp:  @kadirnar

**Comment by kadirnar** [comment]
Thank you for the answer😇
