### ISSUE TITLE
coco2fiftyone has no add_coco_labels function

### ISSUE THREAD

**Issue by wyzhu234** [obss/sahi#539]
Hi, there are some problems when running coco2fiftyone script, errors traced as flow:
Uncaught exception
Traceback (most recent call last):
  File "/homeDL/pytorch/sahi/led/coco2fiftyone.py", line 10, in <module>
    coco2fiftyone(
  File "/home/anaconda3/envs/sahi/lib/python3.8/site-packages/sahi/scripts/coco2fiftyone.py", line 24, in main
    from sahi.utils.fiftyone import add_coco_labels, create_fiftyone_dataset_from_coco_file, fo
ImportError: cannot import name 'add_coco_labels' from 'sahi.utils.fiftyone' 
Does the function is not implement?

**Comment by fcakyon** [comment]
@wyzhu234 what are your `sahi` and `fiftyone` versions?

**Comment by fcakyon** [comment]
@wyzhu234 you are most likely using an outdated version of `sahi` because there is no such function inhttps://github.com/obss/sahi/blob/23b27545f665414d938c2e199eddc6a43a53e578/sahi/utils/fiftyone.py#L67

```bash
pip install -U sahi
```

would fix your issues.

**Comment by fcakyon** [comment]
Thanks a lot for reporting this bug! You can use the fixed version with `pip install -U git+https://github.com/obss/sahi.git@fix-fo`

**Comment by wyzhu234** [comment]
Thank you for your timely update and help

**Comment by fcakyon** [comment]
@wyzhu234 thanks for reporting! Fix is live on new version: https://github.com/obss/sahi/releases/tag/0.10.3

`pip install -U sahi` would be enough now.
