### ISSUE TITLE
Use Sahi to achieve Object_Counting 

### ISSUE THREAD

**Issue by rushbbbbb** [obss/sahi#545]

**Comment by rushbbbbb** [comment]
In yolov5, I can revise detect.py to get the number of Object Detection.But in Sahi I don't konw how to do it.
Hope you can help me.
Thanks!

**Comment by fcakyon** [comment]
@rushbbbbb can you be more specific? You can get total number of detections as:

```python
result = get_sliced_prediction(
    "demo_data/small-vehicles1.jpeg",
    detection_model,
    slice_height = 512,
    slice_width = 512,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2,
)
num_detections = len(result.object_prediction_list)

```

**Comment by rushbbbbb** [comment]
> Use Sahi to achieve Object_Counting
(Sorry.My poor Enlish  expressed badly)

**Comment by devrimcavusoglu** [comment]
@rushbbbbb is your problem solved, or question answered ? If not, maybe you can use google translate or sth simply ? :slightly_smiling_face:

**Comment by rushbbbbb** [comment]
Solved,thank you for your concern.
