### ISSUE TITLE
model inheritance fails due to check_requirements

### ISSUE THREAD

**Issue by davidblom603** [obss/sahi#547]
We cannot create a class which inherits from the MmdetDetectionModel due to the `check_requirements` line.

https://github.com/obss/sahi/blob/main/sahi/model.py#L183

The class is somehow transformed to a function.

**Comment by fcakyon** [comment]
@davidblom603 thanks for reporting, I will push a fix today 👍

**Comment by davidblom603** [comment]
Thank you!

**Comment by fcakyon** [comment]
@davidblom603 can you try ```pip install git+https:github.com/obss/sahi.git@refactor-chackreqs``` and say if it solves your issue?

**Comment by davidblom603** [comment]
It works! Thank you!
