### ISSUE TITLE
COCO format polygons

### ISSUE THREAD

**Issue by ninafiona** [obss/sahi#552]
The resulting segmentations from SAHI are filled polygons. As far as I know coco format segmentations are usually a list of polygon vertices. I am training using detectron, can that be an issue?

**Comment by fcakyon** [comment]
What do you mean by filled polygons? You can convert COCO segmentation points into SAHI annotation object: https://github.com/obss/sahi/blob/188b279dd82f5eb2bedd5a2560f9013cd3fbb209/sahi/annotation.py#L319

or convert SAHI annotation/prediction objects into COCO segmentation points: https://github.com/obss/sahi/blob/188b279dd82f5eb2bedd5a2560f9013cd3fbb209/sahi/annotation.py#L567

SAHI mask annotations can be directly converted into COCO segmentation point list: https://github.com/obss/sahi/blob/188b279dd82f5eb2bedd5a2560f9013cd3fbb209/sahi/annotation.py#L267

**Comment by fcakyon** [comment]
@ninafiona check detectron2 demo notebook line9 an example usage: https://github.com/obss/sahi/blob/main/demo/inference_for_detectron2.ipynb
