### ISSUE TITLE
Is there a way to adjust model resolution for sliced prediction?

### ISSUE THREAD

**Issue by sezer-muhammed** [obss/sahi#562]
I found from codes we can do that: yolov5inferencemodel.image_size = some_int

but is there an another way to adjust and monitor image size?

**Comment by fcakyon** [comment]
Currently preferred way of setting model image size is while creating a DetectionModel instance as

```python
from sahi import AutoDetectionModel

detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov5',
    model_path='yolov5s.pt',
    image_size=640,
)
```

or

```python
from sahi.models import Yolov5DetectionModel

detection_model = Yolov5DetectionModel(
    model_path='yolov5s.pt',
    image_size=640,
)
```

**Comment by fcakyon** [comment]
If this is not answering your question, feel free to ask follow-up questions :)
