### ISSUE TITLE
Error using sliced inference on custom yolov5 model

### ISSUE THREAD

**Issue by wish2023** [obss/sahi#563]
I’d like to perform sliced interference on a custom yolov5 model and have followed the demo notebook and just changed the `model_path`. Here’s my code:

```
import os
# from sahi.utils.yolov5 import (
#     download_yolov5s6_model,
# )

# import required functions, classes
from sahi.model import Yolov5DetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict
from IPython.display import Image


model_path = "/home/user/Desktop/yolov5/best.pt"
image_path = "/home/user/Desktop/yolov5/data/images/image.png"

# download_yolov5s6_model(destination_path=model_path)

detection_model = Yolov5DetectionModel(
    model_path=model_path,
    confidence_threshold=0.3,
    device='cpu', # or 'cuda:0'
)

result = get_sliced_prediction(
    image_path,
    detection_model,
    slice_height = 256,
    slice_width = 256,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)

result.export_visuals(export_dir="samples/")
```

The weights of my custom model work when I use yolov5’s `detect.py` without sliced inference

When I perform sliced inference I get the following:

`TypeError: ('model_path is not a valid yolov5 model path: ', AttributeError("Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/user/Desktop/yolov5/venv/lib/python3.8/site-packages/yolov5/models/yolo.py'>"))`

However, sliced interference works when I change `model_path` to `yolov5s6.pt` or `yolo5s.pt`. 
Please advise on the changes required. Thank you :))

**Comment by fcakyon** [comment]
Thanks for your interest!

What are your yolov5 and sahi versions?

**Comment by wish2023** [comment]
I have yolov5 6.1.8 and sahi 0.10.4

**Comment by fcakyon** [comment]
This is a yolov5 issue. Currently yolov5==6.1.8 do not support the 6.2 update from ultralytics.

**Comment by eVen-gits** [comment]
Hello!

First of all, I love your project. It's enabled us to work on certain problems with large images.

Are there plans to support yolov5 vesion 6.2, or is there another issue? I am getting the same error regarding incompatibility. Is there a way to resolve it, or where is the issue?

Thanks!

**Comment by fcakyon** [comment]
@eVen-gits @wish2023 you can use `sahi` with yolov5 6.2 after updating your yolov5 package with `pip install yolov5==6.2.0`
