### ISSUE TITLE
YOLOv7 Support

### ISSUE THREAD

**Issue by emersondelemmus** [obss/sahi#564]
Hello, I am trying to run slicing inference using a custom dataset trained YOLOv7. Does SAHI support YOLOv7? 

Command: 

`sahi predict --source C:\yolov7-master\dataset\test\images --model_path C:\yolov7-master\yolov7-main\runs\train\yolov7\weights\best.pt --model_config_path C:\yolov7-master\yolov7-main\cfg\training\yolov7.yaml --slice_height 640 --slice_width 640 --model_confidence_threshhold 0.3`

I installed: pip install yolov7, and then it required me to install mmdet (which is odd since YOLOv5 did not require that). 

ERROR: ![Capture](https://user-images.githubusercontent.com/26555905/185444310-bb7cc4a1-2a21-405b-8eed-54b7bb0ca5f9.PNG)

**Comment by fcakyon** [comment]
SAHI currently doesnt support yolov7, there is related PR, you can try that.

When you dont add ‘—model_type’ argument ‘sahi predict’ command assumes its mmdet model.

**Comment by kadirnar** [comment]
Hi @emersondelemmus ,

Yolov7 + SAHI(Demo): https://github.com/obss/sahi/blob/ee1c1f3fdd037c0b018b0892836545b40c04c0ba/demo/inference_for_yolov7.ipynb

**Comment by sejr1996** [comment]
Does anyone know how to get the mask of a model trained with yolov7? I am getting None as the value of the mask.
