### ISSUE TITLE
run NMS on empty bounding box from one of ensembled models

### ISSUE THREAD

**Issue by ramdhan1989** [obss/sahi#569]
Hi, I tried to ensemble 5 models. if there is no bounding box detected from one of 5 models, the nms gives error as follow :
```
ValueError                                Traceback (most recent call last)
Input In [39], in <cell line: 14>()
     12 lebar = dict_pred[img.split('\\')[-1].split('.')[0]]['image_width']
     13 tinggi = dict_pred[img.split('\\')[-1].split('.')[0]]['image_height']
---> 14 boxes, scores, labels = nms_method(bbox_list, conf_list, cat_list, method=2, weights=weights, iou_thr=0.3, sigma=0.05, thresh=0.001)

File ~\Anaconda3\envs\SiT\lib\site-packages\ensemble_boxes\ensemble_boxes_nms.py:187, in nms_method(boxes, scores, labels, method, iou_thr, sigma, thresh, weights)
    184             scores[i] = (np.array(scores[i]) * weights[i]) / weights.sum()
    186 # We concatenate everything
--> 187 boxes = np.concatenate(boxes)
    188 scores = np.concatenate(scores)
    189 labels = np.concatenate(labels)

File <__array_function__ internals>:5, in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 3 has 1 dimension(s)
```
If I used wbf method, it runs succesfully. is there any solution to run nms in this situation like wbf does. please advise

thank you
regards

**Comment by fcakyon** [comment]
Hello @ramdhan1989, can you provide a reproducible code example so that we see which functions and modules are called?

**Comment by ramdhan1989** [comment]
Dear team,
I apologize, my previous question seems not related with this repo. I changed my question if that would be ok.

thanks

**Comment by fcakyon** [comment]
You can find TTA examples for Detectron2, MMDetection, HuggingFace and Torchvision models here: https://github.com/obss/sahi/tree/main/demo

**Comment by ramdhan1989** [comment]
I have checked the notebooks. However, I couldn't find the syntax that used to activate or deactivate TTA during inference. would you mind elaborating more about the TTA option in the code?

thanks

**Comment by ramdhan1989** [comment]
Ok noted
thanks for your information
