### ISSUE TITLE
detect only choosen classes

### ISSUE THREAD

**Issue by MyraBaba** [obss/sahi#578]
Hi,

How we can limit the --classes 1 2 3 4 9 33 like ?

Best

**Comment by MyraBaba** [comment]
@sinanonur 
Is there any change to run videos only for choosen classes not all ?

**Comment by fcakyon** [comment]
@MyraBaba currently sahi does not support that, you can update the scripts to include that filtering. We are also open to any PR, you can open a PR including this feature 👍
