### ISSUE TITLE
detect objects in cropped images of a bigger image

### ISSUE THREAD

**Issue by bit-scientist** [obss/sahi#588]
I have some questions before I use SAHI. Could you help me understand the method in more detail?

Let's say I have an [image ](https://www.freepik.com/free-photos-vectors/cat-background) with 3840x2160 size and I cropped it into 9 regions which makes each tile image's size 1280x720. (The image below is just an example )
![image](https://user-images.githubusercontent.com/26497571/190379482-b004d291-4cb8-4998-a538-0adeb3ac2794.png)

Then I annotated the 1280x720 image with bbox to train with yolov5m. Since the cropped image's size is 1280x720, I chose `python path/to/train.py --data cat_dataset.yaml --weights yolov5s.pt --img 1280` for training. 

For inference, I first send the original image (3840x2160) to a cropping function to prepare 9 crops, then send those 9 to the trained model. Objects in each smaller crops generate bboxes, but I need to draw the whole bbox on the whole image. The issue emerges here, I don't know how to merge individual bboxes of each crop into one bigger bbox. 

So, the question:
1. If I use SAHI,  with what resolution should I train the dataset, 3840x2160 or 1280x720?

I decided to crop images due to the following reasons:
- objects are very small (1-2%) compared to original image;
- objects are cluttered with background, so it's easier to crop and then annotate smaller images where objects appear;
- 4K image training doesn't seem right when considering all yolo models were trained with up to 1280 img-size.

I hope you can guide me correctly.
Thank you for the great work.

**Comment by fcakyon** [comment]
Thanks for your interest in SAHI!

You should train the model with 1280-sized slices. Then you should use slice height, width as 720, 1280 and `image_size=1280` in SAHI.

**Comment by bit-scientist** [comment]
Amazing. Thank you a lot, @fcakyon
