### ISSUE TITLE
Questions about postprocessing when using Yolov5

### ISSUE THREAD

**Issue by youngjae-avikus** [obss/sahi#606]
Hello
A demo test is conducted using Yolov5, and if I use the default parameter, it is wrapped in the `Autoshape` class and is forwarded
Then basically, it looks like doing `NMM` again after the included `NMS`, is this right?
I don't think there will be a problem even if I mix the two, but is there any problem in this area?

THANK YOU

**Comment by fcakyon** [comment]
@youngjae-avikus thanks for the question.

There are two use-case for SAHI:

a. don't perform sliced-inference:
  - SAHI doesn't apply postprocess, only postprocess from yolov5/mmdet/detectron2 is performed.
b. perform sliced-inference:
    1. yolov5/mmdet etc performs prediction and applies postprocess for each single slice
    2. SAHI combines slice prediction results
    3. SAHI applies postprocess to combined results
    
So detector postprocess and SAHI postprocess are different and both are required.
