### ISSUE TITLE
conda installation fails on python 3.8

### ISSUE THREAD

**Issue by OscylO** [obss/sahi#74]
Failes to install on conda with python 3.8 works on 3.6. :(

**Comment by fcakyon** [comment]
@OscylO can you send the error log?

Have you tried `pip install sahi`?

**Comment by OscylO** [comment]
I have not tried pip installation but what I know from log and manual installation of all dependencies the problem was imantics package. So your fix should work. Thank you for fast response and cool library.

**Comment by fcakyon** [comment]
Great to hear that :) will notice you when new release is published (will be in an hour).

**Comment by fcakyon** [comment]
@OscylO its up, try `conda install sahi=0.3.15 -c obss`
